"""Artificial Intelligence city quizzes."""

LEVELS = {
    "l1": {
        "PEAS": [
            ("What does PEAS stand for?",
             "Performance measure, Environment, Actuators, Sensors",
             ["Planning, Execution, Action, Search", "Perception, Evaluation, Algorithms, Systems", "Policy, Estimation, Agents, States"],
             "PEAS is the standard way to specify an agent's task."),
            ("For a self-driving car, the steering wheel and brakes are…",
             "Actuators",
             ["Sensors", "The performance measure", "The environment"],
             "Actuators are how the agent acts on the world."),
            ("A good performance measure for a spam filter is…",
             "Catching spam while rarely blocking real email",
             ["The number of emails received", "The color of the inbox", "The CPU brand"],
             "Performance measures score the outcomes the designer cares about."),
            ("A robot's camera and lidar are its…",
             "Sensors",
             ["Actuators", "Performance measure", "Environment"],
             "Sensors are how the agent perceives the world."),
            ("Why write down PEAS before designing an agent?",
             "It defines the task clearly before choosing an approach",
             ["Python requires it", "It picks the programming language", "It replaces training"],
             "You can't build a good agent without knowing what 'good' means."),
        ],
        "Environments": [
            ("Chess played without a clock is…",
             "Fully observable",
             ["Partially observable", "Stochastic", "Continuous"],
             "Both players can see the entire board."),
            ("Poker is…",
             "Partially observable, since opponents' cards are hidden",
             ["Fully observable", "Deterministic and single-agent", "Continuous"],
             "The agent must reason about information it can't see."),
            ("In a stochastic environment…",
             "The next state isn't fully determined by the current state and action",
             ["Every action always has the same outcome", "There are no states", "There is only ever one agent"],
             "Randomness means the agent must plan for multiple outcomes."),
            ("Driving a taxi in a city is…",
             "Dynamic, continuous and multi-agent",
             ["Static, discrete and single-agent", "Fully observable and episodic", "Deterministic"],
             "The world changes while the agent thinks, and other drivers act too."),
            ("Classifying separate, independent photos on an assembly line is…",
             "Episodic",
             ["Sequential", "Adversarial", "Continuous-time"],
             "Each decision doesn't affect the next one."),
        ],
        "Rationality": [
            ("A rational agent…",
             "Acts to maximize its expected performance given its percepts and knowledge",
             ["Always knows the future", "Acts randomly", "Copies human behavior"],
             "Rationality is about expected outcomes, not perfect ones."),
            ("How does rationality differ from omniscience?",
             "Rational agents maximize expected outcomes; omniscient ones know actual outcomes",
             ["They are the same thing", "Omniscience is the weaker property", "A rational agent never makes mistakes"],
             "A rational agent can still be unlucky."),
            ("A simple reflex agent…",
             "Acts only on the current percept, using condition-action rules",
             ["Plans many steps ahead", "Learns from its full history", "Maximizes a utility function"],
             "It has no memory of past percepts."),
            ("A utility-based agent chooses actions that…",
             "Maximize a utility function over states",
             ["Follow fixed rules only", "Ignore goals entirely", "Are picked at random"],
             "Utility lets it compare how good different outcomes are."),
            ("Why does learning matter for rationality?",
             "It lets the agent improve when its initial knowledge is incomplete",
             ["Learning makes agents irrational", "It is never needed", "It replaces sensors"],
             "Learning agents can adapt to environments their designers didn't fully know."),
        ],
    },
    "l2": {
        "BFS / DFS": [
            ("Breadth-first search uses which data structure for its frontier?",
             "A queue (FIFO)",
             ["A stack (LIFO)", "A priority queue ordered by heuristic", "Only a hash set"],
             "BFS expands the oldest node first, level by level."),
            ("Depth-first search uses…",
             "A stack (LIFO) or recursion",
             ["A queue", "A min-heap", "No data structure"],
             "DFS always expands the most recently discovered node."),
            ("When every step costs the same, BFS finds…",
             "The path with the fewest steps",
             ["The longest path", "A random path", "The deepest path"],
             "It explores all paths of length k before length k + 1."),
            ("What is a risk of DFS in very deep or infinite search spaces?",
             "It can go down an endless branch and never find a solution",
             ["It uses too little memory to work", "It is always optimal", "It can't backtrack"],
             "Depth-limited or iterative deepening search fixes this."),
            ("What is DFS's memory advantage over BFS?",
             "It stores only the current path, while BFS's frontier grows exponentially",
             ["BFS actually uses less memory", "They always use the same memory", "DFS needs no memory at all"],
             "DFS memory is O(bm); BFS is O(b^d)."),
        ],
        "A* Search": [
            ("A* ranks frontier nodes by…",
             "f(n) = g(n) + h(n)",
             ["h(n) only", "g(n) only", "g(n) × h(n)"],
             "Cost so far plus estimated cost to the goal."),
            ("In A*, what is g(n)?",
             "The actual cost from the start to n",
             ["The estimated cost from n to the goal", "The depth of n", "The number of neighbors of n"],
             "h(n) is the estimate; g(n) is the known cost."),
            ("A* (tree search) is optimal when the heuristic is…",
             "Admissible: it never overestimates",
             ["Overestimating", "Random", "Ignored in favor of g"],
             "An optimistic estimate never hides the best path."),
            ("If h(n) = 0 for every node, A* behaves like…",
             "Uniform-cost search (Dijkstra)",
             ["Depth-first search", "Greedy best-first search", "It fails"],
             "Without a heuristic, it orders nodes purely by g(n)."),
            ("How does greedy best-first search differ from A*?",
             "It uses only h(n), ignoring the cost so far",
             ["It uses only g(n)", "They are identical", "It uses a FIFO queue"],
             "That makes it fast but not guaranteed to be optimal."),
        ],
        "Heuristics": [
            ("What is a heuristic in search?",
             "An estimate of the cost from a node to the goal",
             ["Always the exact cost", "A random number", "The number of steps taken so far"],
             "A good heuristic guides search toward the goal."),
            ("On a grid with 4-directional moves, which heuristic is admissible?",
             "Manhattan distance",
             ["Manhattan distance × 10", "The number of steps taken so far", "A random value"],
             "You need at least |dx| + |dy| moves, so it never overestimates."),
            ("A consistent heuristic satisfies…",
             "h(n) ≤ cost(n, n') + h(n') for every neighbor n'",
             ["h(n) = 0 everywhere", "h grows along every path", "h(n) = g(n)"],
             "It is a triangle inequality; consistency implies admissibility."),
            ("If h₁ ≥ h₂ everywhere and both are admissible, A* with h₁…",
             "Expands no more nodes than with h₂",
             ["Is worse than with h₂", "Behaves exactly the same", "Fails to find a solution"],
             "A dominating heuristic is more informed."),
            ("A common admissible heuristic for the 8-puzzle is…",
             "The number of misplaced tiles",
             ["The total moves made so far", "Correctly placed tiles × 2", "A random number"],
             "Each misplaced tile needs at least one move."),
        ],
    },
    "l3": {
        "Logic": [
            ("In propositional logic, 'P → Q' is false only when…",
             "P is true and Q is false",
             ["P is false and Q is true", "Both are false", "Both are true"],
             "An implication is only broken by a true premise with a false conclusion."),
            ("What does modus ponens let you infer?",
             "From P and P → Q, infer Q",
             ["From Q, infer P", "From ¬P, infer ¬Q", "From P, infer ¬P"],
             "It is the most basic sound inference rule."),
            ("What does first-order logic add over propositional logic?",
             "Quantifiers (∀, ∃) and relations over objects",
             ["Only true/false constants", "Probabilities", "Neural network weights"],
             "You can make statements about all or some objects."),
            ("What does '∀x Human(x) → Mortal(x)' mean?",
             "Every human is mortal",
             ["Some human is mortal", "No humans are mortal", "Every mortal thing is human"],
             "∀ means 'for all'."),
            ("A sound inference procedure…",
             "Only derives sentences that are actually entailed",
             ["Derives every possible sentence", "Always finds every entailed sentence", "Guesses conclusions"],
             "Soundness means no false conclusions; completeness means none are missed."),
        ],
        "Ontologies": [
            ("What is an ontology in AI?",
             "A formal specification of concepts, categories and relationships in a domain",
             ["A database backup", "A neural network layer", "A search algorithm"],
             "It defines a shared vocabulary machines can reason with."),
            ("Which is an 'is-a' relationship?",
             "A dog is a mammal",
             ["A dog has a tail", "A dog eats food", "A dog is 5 years old"],
             "'is-a' is subclass membership, which supports inheritance."),
            ("Which language is the standard for web ontologies?",
             "OWL",
             ["CSS", "SQL", "YAML"],
             "The Web Ontology Language builds on RDF."),
            ("Why are ontologies useful?",
             "They give a consistent shared vocabulary and enable automated reasoning",
             ["They compress images", "They make GPUs faster", "They replace data"],
             "Systems can combine and query knowledge reliably."),
            ("Which is a 'part-of' relationship?",
             "A wheel is part of a car",
             ["A car is a vehicle", "A car costs money", "A car is red"],
             "Part-of (meronymy) differs from is-a (subclass)."),
        ],
        "Frames": [
            ("What is a frame in knowledge representation?",
             "A structured description of a typical object or situation, with slots and fillers",
             ["A single video frame", "A kind of loop", "A network packet"],
             "Minsky introduced frames for stereotyped knowledge."),
            ("What are the slots in a frame?",
             "Attributes (like color or owner) that hold values",
             ["Physical ports", "Time steps", "Neurons"],
             "A 'Car' frame might have slots for make, color and owner."),
            ("What is a default value in a frame?",
             "A value assumed unless more specific information overrides it",
             ["A value that can never change", "A random value", "An error code"],
             "For example, 'birds fly' unless the frame is for a penguin."),
            ("How do frames support inheritance?",
             "Child frames inherit slot values from parent frames",
             ["By copying files", "Through genetic algorithms", "They don't"],
             "A 'Sparrow' frame inherits from 'Bird'."),
            ("Frames are closely related to…",
             "Classes and objects in object-oriented programming",
             ["SQL joins", "Pixel arrays", "Audio waveforms"],
             "Both group attributes and inherit from more general types."),
        ],
    },
    "l4": {
        "Tokenization": [
            ("What is tokenization?",
             "Splitting text into units like words or subwords",
             ["Translating text", "Encrypting text", "Counting pages"],
             "Tokens are the basic units a language model processes."),
            ("Why use subword tokenization such as BPE?",
             "It handles rare or unknown words by building them from pieces",
             ["It removes the vocabulary", "It is always slower", "It only works on images"],
             "Any word can be represented without a huge vocabulary."),
            ("A subword tokenizer might split 'unhappiness' into…",
             "'un' + 'happi' + 'ness'",
             ["A single <UNK> token", "The number 0", "The whole sentence it came from"],
             "Common pieces are reused across many words."),
            ("What are stop words?",
             "Very common words like 'the' and 'is', often filtered in classic pipelines",
             ["Only punctuation", "Rare words", "Only end-of-sentence markers"],
             "They carry little meaning for tasks like keyword search."),
            ("Which is a common text-normalization step before tokenizing?",
             "Lowercasing and Unicode normalization",
             ["Adding typos", "Shuffling the words", "Translating to another language"],
             "Normalization makes 'Apple' and 'apple' match when that's wanted."),
        ],
        "Embeddings": [
            ("What is a word embedding?",
             "A dense vector where similar words end up close together",
             ["A one-hot vector the size of the vocabulary", "A file of definitions", "A word count"],
             "Embeddings capture meaning in a few hundred dimensions."),
            ("In classic word embeddings, king − man + woman ≈ …",
             "queen",
             ["prince", "kingdom", "man"],
             "Relationships show up as consistent vector offsets."),
            ("Which measure is commonly used to compare embeddings?",
             "Cosine similarity",
             ["String length", "Alphabetical order", "File size"],
             "It compares direction regardless of vector length."),
            ("How does Word2Vec learn embeddings?",
             "By predicting words from their nearby context (or vice versa)",
             ["By sorting the dictionary", "By hand-labeling every word", "By counting letters"],
             "Words that appear in similar contexts get similar vectors."),
            ("What is the advantage of contextual embeddings such as BERT's?",
             "The same word gets different vectors in different contexts",
             ["Every word has exactly one fixed vector", "They need no training", "They are always smaller than one-hot vectors"],
             "'bank' by a river differs from 'bank' with money."),
        ],
        "Parsing": [
            ("What is syntactic parsing?",
             "Working out the grammatical structure of a sentence",
             ["Reading files from disk", "Only spell checking", "Translating text"],
             "It produces a tree of how the words relate."),
            ("A dependency parse represents…",
             "Head–dependent relations between words",
             ["Word frequencies", "Phrase colors", "Sentiment scores"],
             "For example, 'dog' is the subject of 'barks'."),
            ("What does part-of-speech tagging do?",
             "Labels each word as a noun, verb, adjective and so on",
             ["Translates each word", "Counts the words", "Removes the words"],
             "POS tags are often the first step before parsing."),
            ("'I saw the man with the telescope' is an example of…",
             "Structural (attachment) ambiguity",
             ["A tokenization error", "A spelling error", "An unambiguous sentence"],
             "Who has the telescope depends on where the phrase attaches."),
            ("Context-free grammars are used to…",
             "Define phrase-structure rules for parsing",
             ["Store embeddings", "Compress text", "Generate images"],
             "Rules like S → NP VP describe valid sentence structures."),
        ],
    },
    "l5": {
        "Pixels & Filters": [
            ("How is a grayscale image stored?",
             "As a 2-D grid of intensity values",
             ["As a list of words", "As a 3-D mesh", "As an audio signal"],
             "Each cell is one pixel's brightness."),
            ("What does an RGB pixel contain?",
             "Three values: red, green and blue",
             ["One value", "Always four values", "256 values"],
             "Colors are mixed from the three channel intensities."),
            ("What does a Gaussian blur filter do?",
             "Smooths the image by averaging neighbors with Gaussian weights",
             ["Sharpens edges", "Detects faces", "Rotates the image"],
             "It is often used to reduce noise."),
            ("What does a Sobel filter do?",
             "Detects edges by estimating intensity gradients",
             ["Blurs the image", "Changes its colors", "Compresses it"],
             "Large gradients mark sharp changes in brightness."),
            ("What range does an 8-bit color channel cover?",
             "0–255",
             ["0–1023", "0–100", "1–8"],
             "8 bits give 2⁸ = 256 levels."),
        ],
        "Detection": [
            ("What does object detection output?",
             "Class labels and bounding boxes for each object",
             ["A single label for the image", "Only a pixel mask", "A text caption"],
             "Detection answers both 'what' and 'where'."),
            ("What is IoU (Intersection over Union)?",
             "The overlap area divided by the union area of two boxes",
             ["A box's width", "The number of boxes", "The image's pixel count"],
             "It measures how well a predicted box matches the true one."),
            ("What does non-maximum suppression do?",
             "Removes overlapping duplicate boxes, keeping the highest-scoring one",
             ["Adds more boxes", "Blurs the image", "Resizes the image"],
             "Detectors often fire several times on one object."),
            ("YOLO is known as…",
             "A single-stage detector that predicts boxes in one pass",
             ["A two-stage detector with region proposals", "A segmentation-only model", "A text model"],
             "'You Only Look Once' trades a little accuracy for speed."),
            ("What does mAP measure in detection?",
             "Mean average precision across classes (and IoU thresholds)",
             ["The maximum area of pixels", "The mean pixel value", "The number of model parameters"],
             "It is the standard detection benchmark score."),
        ],
        "Segmentation": [
            ("What does semantic segmentation do?",
             "Labels every pixel with a class",
             ["Gives one label per image", "Draws boxes only", "Writes captions"],
             "It gives a dense, pixel-level understanding of the image."),
            ("How does instance segmentation differ from semantic segmentation?",
             "It separates individual objects of the same class",
             ["It ignores classes", "They are identical", "It only draws boxes"],
             "Two people get two different masks, not one 'person' region."),
            ("Which architecture is popular for medical image segmentation?",
             "U-Net",
             ["LSTM", "k-means alone", "A decision tree"],
             "Its encoder–decoder shape with skip connections suits pixel labels."),
            ("Which metric is common for segmentation masks?",
             "Dice coefficient / IoU",
             ["BLEU", "Perplexity", "R²"],
             "Both measure overlap between predicted and true masks."),
            ("What do U-Net's skip connections do?",
             "Carry fine spatial detail from the encoder to the decoder",
             ["Reduce the parameters to zero", "Shuffle the pixels", "Add class labels"],
             "They restore detail lost by downsampling."),
        ],
    },
    "l6": {
        "State Space": [
            ("What is a state space?",
             "The set of all possible configurations and the actions that connect them",
             ["A memory address range", "Empty space on screen", "GPU memory"],
             "Planning searches this space for a path to the goal."),
            ("What is a plan?",
             "A sequence of actions from the initial state to a goal",
             ["A single state", "A heuristic value", "A list of sensors"],
             "Executing the plan should reach the goal."),
            ("What is forward (progression) search?",
             "Start at the initial state and apply actions toward the goal",
             ["Start at the goal", "Jump between random states", "Take no actions"],
             "It simulates the world moving forward."),
            ("What is backward (regression) search?",
             "Start from the goal and work back through actions that achieve it",
             ["Start from the initial state", "Search images in both directions", "Search without actions"],
             "It only considers actions relevant to the goal."),
            ("Why are state spaces hard to search?",
             "The number of states grows exponentially with the number of variables",
             ["They are always small", "There are no actions", "They only grow linearly"],
             "n true/false facts give 2ⁿ possible states."),
        ],
        "STRIPS": [
            ("How is a STRIPS action described?",
             "By preconditions, an add list and a delete list",
             ["By inputs, outputs and weights", "By nodes and edges", "By key–value pairs"],
             "These say when an action applies and how it changes the world."),
            ("What is a precondition?",
             "A fact that must be true before the action can be applied",
             ["A fact added afterward", "The goal", "The action's cost"],
             "For example, you must hold a key to unlock a door."),
            ("What is the delete list?",
             "Facts that become false after the action",
             ["Facts that become true", "Facts that stay the same", "The goals"],
             "Picking up a block deletes 'hand empty'."),
            ("What is STRIPS's closed-world assumption?",
             "Any fact not stated is false",
             ["Every fact is true", "Unstated facts are unknown", "Facts are random"],
             "The state lists only what is true."),
            ("What is PDDL?",
             "A standard language, descended from STRIPS, for describing planning problems",
             ["A GPU programming language", "A database", "A CSS framework"],
             "Planning competitions use PDDL."),
        ],
        "Hierarchical Plans": [
            ("How does HTN (Hierarchical Task Network) planning work?",
             "It decomposes high-level tasks into subtasks until only primitive actions remain",
             ["It flattens tasks into a random order", "It uses only one action", "It ignores goals"],
             "It resembles how people break down big jobs."),
            ("Which is a hierarchical decomposition?",
             "'Travel to Paris' → book a flight, get to the airport, fly",
             ["Adding facts to a delete list", "Tokenizing words", "Blurring an image"],
             "A compound task is refined into smaller steps."),
            ("What is the main advantage of HTN planning?",
             "Domain knowledge about task structure greatly reduces search",
             ["It needs no knowledge", "It is always optimal", "It needs no actions"],
             "Methods rule out orderings that make no sense."),
            ("What is a primitive task?",
             "One that can be executed directly without further decomposition",
             ["One that needs decomposition", "Only a goal", "A sensor"],
             "Primitive tasks correspond to real actions."),
            ("What is a 'method' in HTN planning?",
             "A recipe for one way to decompose a compound task",
             ["Any Python method", "A sensor reading", "A heuristic number"],
             "A task can have several methods for different situations."),
        ],
    },
    "l7": {
        "Bayes Nets": [
            ("What is a Bayesian network?",
             "A directed acyclic graph with conditional probability tables",
             ["An undirected graph with cycles", "Just a neural network", "A decision tree"],
             "Nodes are variables; edges show direct dependence."),
            ("An edge A → B means…",
             "B's probability depends directly on A",
             ["A always causes B", "A and B are independent", "B always happens before A"],
             "Edges encode conditional dependence, not certainty."),
            ("How does a Bayes net factor the joint probability?",
             "As the product of P(node | parents)",
             ["As the sum over all nodes", "As a maximum", "As the product of marginals"],
             "That factorization is what keeps it compact."),
            ("What is Bayes' rule?",
             "P(A|B) = P(B|A)·P(A) / P(B)",
             ["P(A|B) = P(A)·P(B)", "P(A|B) = P(B|A) / P(A)", "P(A|B) = P(A) + P(B)"],
             "It turns P(evidence | cause) into P(cause | evidence)."),
            ("What is the main benefit of a Bayes net?",
             "A compact representation that uses conditional independence",
             ["It needs all 2ⁿ joint entries", "It uses no probabilities", "It only handles binary variables"],
             "Each node only needs a table over its parents."),
        ],
        "HMMs": [
            ("In a Hidden Markov Model, the hidden states…",
             "Aren't observed directly; we see emissions that depend on them",
             ["Are always observed", "Don't exist", "Are the labels"],
             "For example, spoken words are hidden and audio is observed."),
            ("What is the Markov assumption?",
             "The next state depends only on the current state",
             ["It depends on the entire history", "It depends on the future", "It is random"],
             "That keeps inference tractable."),
            ("What does the Viterbi algorithm find?",
             "The most likely sequence of hidden states",
             ["The best CNN weights", "A sorted list", "Clusters"],
             "It uses dynamic programming over time steps."),
            ("What is a classic HMM application?",
             "Speech recognition or part-of-speech tagging",
             ["Blurring images", "Sorting numbers", "Web hosting"],
             "Both involve hidden sequences behind observed signals."),
            ("What parameters define an HMM?",
             "Transition probabilities, emission probabilities and an initial distribution",
             ["Weights, biases and a learning rate", "Convolution filters", "Centroids"],
             "These fully specify the generative model."),
        ],
        "Inference": [
            ("What is probabilistic inference?",
             "Computing the probability of query variables given evidence",
             ["Training on images", "Writing SQL", "Compiling code"],
             "For example, P(disease | symptoms)."),
            ("Exact inference in general Bayesian networks is…",
             "NP-hard",
             ["Always O(1)", "Always linear time", "Impossible"],
             "That is why approximate methods matter."),
            ("What does variable elimination do?",
             "Sums out hidden variables one at a time, reusing intermediate factors",
             ["Deletes data", "Removes the evidence", "Picks answers at random"],
             "It avoids enumerating the whole joint distribution."),
            ("Which are approximate inference methods?",
             "Sampling methods such as Gibbs sampling and likelihood weighting",
             ["Only exact enumeration", "Sorting", "Gradient clipping"],
             "More samples give better estimates."),
            ("How do prior and posterior differ?",
             "The prior is before seeing evidence; the posterior is after updating on it",
             ["They are identical", "The posterior comes first", "The prior already includes the evidence"],
             "Bayes' rule turns a prior into a posterior."),
        ],
    },
    "l8": {
        "MDPs": [
            ("What defines a Markov Decision Process?",
             "States, actions, transition probabilities, rewards and a discount factor",
             ["Layers, weights and a loss", "Only nodes and edges", "Tokens"],
             "MDPs are the formal framework for reinforcement learning."),
            ("What does the discount factor γ control?",
             "How much future rewards count compared with immediate ones",
             ["The learning rate", "The number of states", "The amount of exploration"],
             "γ near 1 means far-sighted; near 0 means short-sighted."),
            ("What is a policy?",
             "A mapping from states to actions",
             ["The reward", "The transition function", "The environment"],
             "π(s) tells the agent what to do in each state."),
            ("The Bellman equation relates…",
             "A state's value to the immediate reward plus the discounted value of next states",
             ["Loss to accuracy", "Pixels to labels", "The gradient norm to depth"],
             "V(s) = max_a [R + γ Σ P(s'|s,a) V(s')]."),
            ("With γ = 0, the agent…",
             "Only cares about the immediate reward",
             ["Only cares about the far future", "Acts randomly", "Plans over an infinite horizon"],
             "Every future reward is multiplied by 0."),
        ],
        "Q-Learning": [
            ("What does Q(s, a) represent?",
             "The expected return from taking action a in state s, then acting well",
             ["The quality of the dataset", "The number of actions", "The number of states"],
             "The best action is the one with the highest Q-value."),
            ("What is the Q-learning update?",
             "Q ← Q + α[r + γ·max Q(s', a') − Q]",
             ["Q ← r", "Q ← γ·Q", "Q ← max(r, 0)"],
             "It moves Q toward a bootstrapped target."),
            ("Q-learning is…",
             "Off-policy",
             ["Only on-policy", "Supervised learning", "Unsupervised clustering"],
             "It learns the greedy policy while following an exploratory one."),
            ("What is ε-greedy exploration?",
             "With probability ε take a random action, otherwise the best known one",
             ["Always act randomly", "Always act greedily", "Stop exploring immediately"],
             "It balances exploration and exploitation."),
            ("What is a DQN?",
             "Q-learning with a neural network approximating the Q-values",
             ["A decision tree", "A method with no network", "A purely tabular method"],
             "Deep Q-Networks learned to play Atari games from pixels."),
        ],
        "Policy Gradients": [
            ("Policy gradient methods…",
             "Directly optimize policy parameters by gradient ascent on expected return",
             ["Only learn a Q table", "Cluster the states", "Need supervised labels"],
             "The policy itself is the thing being trained."),
            ("What is REINFORCE?",
             "A Monte Carlo policy gradient that uses sampled returns",
             ["Value iteration", "A* search", "k-means"],
             "It scales log-probability gradients by the return that followed."),
            ("Why subtract a baseline in policy gradients?",
             "To reduce the variance of the gradient estimate",
             ["To add bias on purpose", "To remove rewards", "To add states"],
             "A good baseline keeps the expected gradient but makes it less noisy."),
            ("How do actor-critic methods work?",
             "The actor updates the policy; the critic estimates values to guide it",
             ["Two actors compete", "No value function is used", "A single Q table does everything"],
             "They combine policy-based and value-based learning."),
            ("An advantage of policy-based over value-based methods is…",
             "They handle continuous actions and stochastic policies naturally",
             ["They always have lower variance", "They need no samples", "They have no parameters"],
             "There's no need to take a max over infinitely many actions."),
        ],
    },
    "l9": {
        "Transformers": [
            ("What is the core mechanism of a Transformer?",
             "Self-attention",
             ["Only convolution", "Recurrence", "Decision trees"],
             "'Attention Is All You Need' dropped recurrence entirely."),
            ("How is scaled dot-product attention computed?",
             "softmax(QKᵀ / √d)·V",
             ["QK + V", "max(Q, K)", "V / Q"],
             "Queries score keys, and the scores weight the values."),
            ("Why do Transformers need positional encodings?",
             "Attention ignores order, so position information must be added",
             ["To compress the input", "To add vocabulary", "To remove tokens"],
             "Without them, word order would be invisible to the model."),
            ("GPT-style models are…",
             "Decoder-only models that predict the next token",
             ["Encoder-only masked models", "CNNs", "RNNs"],
             "Causal masking stops a token from seeing later tokens."),
            ("What is multi-head attention?",
             "Several attention heads run in parallel, each attending to different relationships",
             ["Several models voting", "The same layer repeated", "Running on multiple GPUs"],
             "One head might track syntax while another tracks coreference."),
        ],
        "Prompting": [
            ("What is few-shot prompting?",
             "Including a few input–output examples in the prompt",
             ["Fine-tuning on millions of examples", "Sending an empty prompt", "Sending random words"],
             "The model picks up the pattern from the examples."),
            ("What is chain-of-thought prompting?",
             "Asking the model to reason step by step before answering",
             ["Using shorter prompts", "Removing examples", "Only changing the temperature"],
             "It often improves math and logic answers."),
            ("A higher sampling temperature makes output…",
             "More random and diverse",
             ["More deterministic", "Faster", "Always shorter"],
             "Temperature flattens the next-token probability distribution."),
            ("What does a system prompt do?",
             "Sets the model's overall behavior, role and instructions",
             ["Holds the user's last message", "Changes the model's weights", "Replaces the tokenizer"],
             "It frames every later turn in the conversation."),
            ("What is prompt injection?",
             "Malicious input that tries to override the model's instructions",
             ["A technique for faster inference", "SQL indexing", "A prompt template"],
             "For example, 'ignore previous instructions' hidden in a web page."),
        ],
        "RAG": [
            ("What does Retrieval-Augmented Generation do?",
             "Retrieves relevant documents and adds them to the prompt before generating",
             ["Retrains the model for every query", "Gives random answers", "Compresses the model"],
             "The model answers using the retrieved context."),
            ("What is the main benefit of RAG?",
             "Answers are grounded in current or private data, reducing hallucinations",
             ["It removes the need for an LLM", "Training always becomes cheaper", "No retrieval is needed"],
             "The model can cite sources it was never trained on."),
            ("RAG retrieval commonly uses…",
             "Vector similarity search over embeddings",
             ["Alphabetical order", "Random selection", "File size"],
             "Queries and documents are embedded and matched by closeness."),
            ("What is chunking in RAG?",
             "Splitting documents into smaller passages for indexing and retrieval",
             ["Deleting documents", "Merging models", "Tokenizing images"],
             "Smaller chunks give more precise matches."),
            ("What is a common RAG failure mode?",
             "Irrelevant or missing retrieved context leads to wrong answers",
             ["The model can't read text", "The vector database replaces the LLM", "The GPU overheats"],
             "Generation is only as good as what was retrieved."),
        ],
    },
    "l10": {
        "Alignment": [
            ("What is AI alignment?",
             "Making AI systems pursue the goals and values humans intend",
             ["Aligning text in a UI", "Aligning GPUs in a rack", "Sorting data"],
             "A capable but misaligned system can do the wrong thing very well."),
            ("What is RLHF?",
             "Fine-tuning with a reward model trained on human preference comparisons",
             ["Training on random labels", "A kind of hardware", "A compression method"],
             "Reinforcement Learning from Human Feedback."),
            ("What is reward hacking?",
             "Optimizing a proxy reward in ways the designers didn't intend",
             ["Stealing hardware", "Reaching high accuracy", "A tokenizer bug"],
             "The metric goes up while the real goal isn't met."),
            ("Which is an example of specification gaming?",
             "A boat-racing agent circles collecting points instead of finishing the race",
             ["An agent finishing the race normally", "Using a faster GPU", "Data augmentation"],
             "It maximized the written reward, not the intended goal."),
            ("What is scalable oversight?",
             "Ways to supervise AI on tasks too hard for humans to check directly",
             ["Buying bigger monitors", "Adding more GPUs", "Removing humans from the loop"],
             "Examples include debate and AI-assisted evaluation."),
        ],
        "Bias": [
            ("Algorithmic bias most often comes from…",
             "Unrepresentative or historically biased training data",
             ["The GPU brand", "The font", "The screen size"],
             "Models learn the patterns in their data, including unfair ones."),
            ("What does demographic parity require?",
             "Similar positive-prediction rates across groups",
             ["Equal dataset sizes", "The same accuracy for every model", "Identical features"],
             "It is one of several, sometimes conflicting, fairness definitions."),
            ("Why might removing a sensitive attribute not remove bias?",
             "Proxy features such as zip code can still encode it",
             ["The model can't train without it", "Accuracy becomes perfect", "The attribute is needed to compile"],
             "Correlated features leak the same information."),
            ("How do you audit a model for bias?",
             "Evaluate its performance separately for each subgroup",
             ["Only check overall accuracy", "Train for longer", "Run fewer tests"],
             "A good average can hide poor results for a minority group."),
            ("What is a bias feedback loop?",
             "Biased predictions shape future data, which reinforces the bias",
             ["Audio feedback from speakers", "Something that speeds up the model", "A process that removes bias"],
             "Predictive policing is a well-known example."),
        ],
        "Robustness": [
            ("What is an adversarial example?",
             "An input with small, often invisible changes that causes a wrong prediction",
             ["A very large dataset", "A hard exam question", "Just a noisy label"],
             "A few changed pixels can make a panda look like a gibbon to a model."),
            ("What is distribution shift?",
             "Test data that differs from the training distribution",
             ["Moving to new servers", "Changing the batch size", "Swapping GPUs"],
             "Models often fail silently when conditions change."),
            ("What is adversarial training?",
             "Training on adversarial examples to improve robustness",
             ["Removing training data", "Training for fewer epochs", "Training without labels"],
             "The model learns to resist the perturbations it has seen."),
            ("What does out-of-distribution detection do?",
             "Flags inputs that are unlike the training data",
             ["Detects GPU failures", "Sorts the inputs", "Compresses the inputs"],
             "Flagged inputs can be passed to a human instead."),
            ("Why does calibration matter?",
             "Confidence scores should match how often the model is actually right",
             ["It makes the model faster", "It changes the colors", "It doesn't matter"],
             "'90% confident' should mean right about 90% of the time."),
        ],
    },
}
