"""Machine Learning city quizzes."""

LEVELS = {
    "l1": {
        "Weights & Bias": [
            ("In a perceptron, what does each weight represent?",
             "How strongly its input influences the output",
             ["The number of training examples", "The learning rate", "The final class label"],
             "The perceptron computes w·x + b, so a larger |wᵢ| means input xᵢ has more influence."),
            ("What role does the bias term play?",
             "It shifts the decision boundary away from the origin",
             ["It scales every input to the range 0–1", "It counts misclassified points", "It removes the need for weights"],
             "Without a bias the boundary w·x = 0 must pass through the origin; b lets it move."),
            ("With w = [2, −1], b = 0.5 and x = [1, 3], what is w·x + b?",
             "−0.5",
             ["5.5", "1.5", "−1.5"],
             "2·1 + (−1)·3 + 0.5 = 2 − 3 + 0.5 = −0.5."),
            ("If a weight is negative, increasing that input will…",
             "Push the output toward the negative class",
             ["Always push the output toward the positive class", "Have no effect on the output", "Change the bias value"],
             "A negative weight lowers the weighted sum as its input grows."),
            ("Why is the bias often treated as a weight on a constant input of 1?",
             "So it can be learned with the same update rule as the weights",
             ["To make the model nonlinear", "To prevent overfitting", "To double the learning rate"],
             "Adding x₀ = 1 turns b into w₀, so one update rule trains everything."),
        ],
        "Activation Threshold": [
            ("Which activation does the classic perceptron use?",
             "A step function: output 1 if the sum reaches the threshold, else 0",
             ["Softmax", "ReLU", "Tanh"],
             "Rosenblatt's perceptron uses a hard threshold (Heaviside step)."),
            ("With a step activation and threshold 0, what is the output for a weighted sum of −0.2?",
             "0 (the negative class)",
             ["1 (the positive class)", "−0.2", "0.5"],
             "−0.2 is below the threshold, so the step function outputs 0."),
            ("Raising the threshold θ has the same effect as…",
             "Decreasing the bias",
             ["Increasing every weight", "Adding more inputs", "Raising the learning rate"],
             "w·x ≥ θ is the same as w·x − θ ≥ 0, so the bias is b = −θ."),
            ("Why can't gradient descent be applied directly to a step activation?",
             "Its derivative is zero everywhere except at the jump",
             ["It outputs negative numbers", "It is too slow to compute", "It only works on images"],
             "A zero gradient gives no signal about which way to move the weights."),
            ("The decision boundary of a single perceptron is…",
             "A straight line (hyperplane) where w·x + b = 0",
             ["A circle", "Any curve the data needs", "A set of disconnected regions"],
             "The threshold on a linear sum always splits space with a hyperplane."),
        ],
        "Learning Rule": [
            ("When does the perceptron learning rule update the weights?",
             "Only when an example is misclassified",
             ["After every example regardless of correctness", "Only on correct predictions", "Once at the end of training"],
             "If ŷ = y then (y − ŷ) = 0 and nothing changes."),
            ("What is the perceptron update for weight wᵢ?",
             "wᵢ ← wᵢ + η(y − ŷ)xᵢ",
             ["wᵢ ← wᵢ − ηxᵢ on every step", "wᵢ ← wᵢ × η", "wᵢ ← y − ŷ"],
             "The weight moves in the direction that reduces the error on that example."),
            ("The perceptron is guaranteed to converge when…",
             "The data is linearly separable",
             ["The learning rate is exactly 1", "There are more features than samples", "The inputs are normalized"],
             "This is the Perceptron Convergence Theorem."),
            ("Which classic problem can a single perceptron NOT learn?",
             "XOR",
             ["AND", "OR", "NOT"],
             "XOR's positive and negative points can't be split by one straight line."),
            ("What does the learning rate η control?",
             "How big each weight update step is",
             ["The number of layers", "The threshold of the step function", "The number of inputs"],
             "η scales the correction applied after each mistake."),
        ],
    },
    "l2": {
        "Least Squares": [
            ("What does ordinary least squares minimize?",
             "The sum of squared differences between predictions and targets",
             ["The sum of absolute weights", "The number of misclassified points", "Only the single largest error"],
             "OLS minimizes Σ(yᵢ − ŷᵢ)²."),
            ("Why are the errors squared?",
             "It makes every error positive and penalizes large errors more",
             ["It makes the model nonlinear", "It reduces the number of features", "It guarantees zero error"],
             "Squaring removes signs and grows quickly for big mistakes."),
            ("What is the closed-form least-squares solution?",
             "w = (XᵀX)⁻¹Xᵀy",
             ["w = Xy", "w = (XXᵀ)y", "w = y / X"],
             "Setting the gradient of the squared error to zero gives the normal equations."),
            ("For the fitted line y = 2x + 1, what is the prediction at x = 3?",
             "7",
             ["6", "5", "9"],
             "2·3 + 1 = 7."),
            ("What is a known weakness of least squares?",
             "It is sensitive to outliers",
             ["It cannot fit a straight line", "It only works for classification", "It needs categorical targets"],
             "Squaring gives outliers a very large influence on the fit."),
        ],
        "Gradient Descent": [
            ("Gradient descent updates parameters by moving…",
             "Opposite to the gradient of the loss",
             ["In the direction of the gradient", "In a random direction", "Toward the largest parameter"],
             "The gradient points uphill, so we step the other way to reduce the loss."),
            ("What can happen if the learning rate is too large?",
             "The loss can oscillate or diverge",
             ["Training always converges faster with no downside", "The model becomes nonlinear", "The gradient becomes zero"],
             "Big steps can overshoot the minimum again and again."),
            ("How does stochastic gradient descent differ from batch gradient descent?",
             "It updates using one (or a few) examples at a time",
             ["It never computes gradients", "It uses the whole dataset twice per step", "It only works for classification"],
             "SGD trades noisier steps for much cheaper updates."),
            ("For MSE loss, the gradient with respect to a prediction is proportional to…",
             "The error (prediction − target)",
             ["The square of the learning rate", "The number of features", "Always 1"],
             "d/dŷ (ŷ − y)² = 2(ŷ − y)."),
            ("Why use gradient descent instead of the closed-form solution?",
             "It scales better when inverting XᵀX would be too expensive",
             ["It always finds the exact answer in one step", "The closed form can't be computed for linear models", "It needs no data"],
             "Matrix inversion is costly for huge feature counts; GD only needs gradients."),
        ],
        "Residuals": [
            ("What is a residual?",
             "The actual value minus the predicted value",
             ["The predicted value squared", "The slope of the line", "The number of data points"],
             "Residual eᵢ = yᵢ − ŷᵢ."),
            ("In a well-fitted linear model, the residual plot should look like…",
             "Random scatter around zero with no pattern",
             ["A clear U shape", "All positive values", "A steadily increasing line"],
             "Patterns mean the model is missing structure in the data."),
            ("A curved pattern in the residuals suggests…",
             "The relationship is nonlinear and the model is missing it",
             ["The model is perfect", "The learning rate is too small", "The data has no noise"],
             "A straight line can't capture curvature, which then shows up in the residuals."),
            ("If the actual y = 10 and the prediction ŷ = 12, what is the residual?",
             "−2",
             ["2", "22", "0.83"],
             "10 − 12 = −2."),
            ("With an intercept term, ordinary least-squares residuals sum to…",
             "Zero",
             ["The number of samples", "Always a positive number", "The slope"],
             "The intercept's normal equation forces Σeᵢ = 0."),
        ],
    },
    "l3": {
        "Sigmoid": [
            ("What is the sigmoid function?",
             "σ(z) = 1 / (1 + e^(−z))",
             ["σ(z) = e^z", "σ(z) = max(0, z)", "σ(z) = z / (1 + z²)"],
             "It squashes any real number into (0, 1)."),
            ("What is σ(0)?",
             "0.5",
             ["0", "1", "Undefined"],
             "1 / (1 + e⁰) = 1 / 2."),
            ("What is the output range of the sigmoid?",
             "Between 0 and 1",
             ["Between −1 and 1", "0 to infinity", "Any real number"],
             "That range is why it can be read as a probability."),
            ("Why is the sigmoid used in logistic regression?",
             "It converts a linear score into a probability",
             ["It makes the data linearly separable", "It removes the need for weights", "It clusters the data"],
             "p = σ(w·x + b) gives P(y = 1 | x)."),
            ("For a very large positive z, the sigmoid's gradient…",
             "Approaches zero (it saturates)",
             ["Grows without bound", "Equals 1", "Becomes negative"],
             "σ'(z) = σ(z)(1 − σ(z)) → 0 as σ(z) → 1."),
        ],
        "Decision Boundary": [
            ("With a 0.5 threshold, logistic regression's decision boundary is where…",
             "w·x + b = 0",
             ["σ(z) = 1", "w = 0", "x = 0"],
             "σ(z) = 0.5 exactly when z = 0."),
            ("What shape is a plain logistic regression boundary in feature space?",
             "A straight line / hyperplane",
             ["Always a circle", "A zigzag", "A tree"],
             "The boundary is set by a linear function of the inputs."),
            ("How can logistic regression produce a curved boundary?",
             "Add nonlinear features such as x² or x₁x₂",
             ["Increase the learning rate", "Use fewer data points", "Remove the bias"],
             "The model is still linear in its features, but the features are curved in x."),
            ("Raising the threshold from 0.5 to 0.8 usually leads to…",
             "Fewer positive predictions (higher precision, lower recall)",
             ["More positive predictions", "No change at all", "A nonlinear model"],
             "The model now needs more confidence before saying 'positive'."),
            ("If the model outputs p = 0.3 with a 0.5 threshold, the predicted class is…",
             "0",
             ["1", "Both classes", "Undefined"],
             "0.3 < 0.5, so it predicts the negative class."),
        ],
        "Cross Entropy": [
            ("Which loss is standard for logistic regression?",
             "Binary cross-entropy (log loss)",
             ["Mean squared error only", "Hinge loss", "L1 norm of the weights"],
             "It is the negative log-likelihood of Bernoulli labels."),
            ("What is binary cross-entropy for one example?",
             "−[y·log p + (1 − y)·log(1 − p)]",
             ["(y − p)²", "|y − p|", "y / p"],
             "Only the log-probability of the true class contributes."),
            ("If y = 1 and the model predicts p ≈ 0, the loss…",
             "Becomes very large",
             ["Is zero", "Is exactly 0.5", "Becomes negative"],
             "−log(p) → ∞ as p → 0: confident mistakes are punished hard."),
            ("Why prefer cross-entropy over MSE for logistic regression?",
             "It gives a convex loss and strong gradients when confidently wrong",
             ["MSE can't be computed on probabilities", "Cross-entropy needs no labels", "It is shorter to write"],
             "MSE with a sigmoid is non-convex and its gradients vanish when saturated."),
            ("Minimizing cross-entropy is equivalent to…",
             "Maximizing the likelihood of the labels",
             ["Maximizing the number of features", "Shrinking all weights to zero", "Maximizing the learning rate"],
             "Cross-entropy is the negative log-likelihood."),
        ],
    },
    "l4": {
        "Splits & Impurity": [
            ("What is the Gini impurity of a node where every sample has the same class?",
             "0",
             ["0.5", "1", "It depends on the depth"],
             "A pure node has no uncertainty: 1 − 1² = 0."),
            ("A decision tree chooses each split to…",
             "Maximize the reduction in impurity (information gain)",
             ["Maximize the depth of the tree", "Pick a random feature", "Only balance the number of samples"],
             "Greedy splitting picks the most informative question at each node."),
            ("Entropy of a node is highest when…",
             "The classes are equally mixed",
             ["All samples share one class", "The node is empty", "The tree is very deep"],
             "A 50/50 split is maximum uncertainty."),
            ("What is the Gini impurity of a 50/50 two-class node?",
             "0.5",
             ["0", "1", "0.25"],
             "1 − (0.5² + 0.5²) = 0.5."),
            ("A common split criterion for regression trees is…",
             "Reduction in variance (MSE)",
             ["Gini impurity", "Classification accuracy", "Entropy of the features"],
             "Regression targets are continuous, so variance measures node purity."),
        ],
        "Pruning": [
            ("Why prune a decision tree?",
             "To reduce overfitting by removing branches that don't generalize",
             ["To make the tree deeper", "To increase training accuracy", "To add more features"],
             "Deep branches often memorize noise in the training data."),
            ("Which is an example of pre-pruning?",
             "Limiting max_depth or the minimum samples per leaf",
             ["Removing subtrees after full growth", "Bagging many trees", "Normalizing the features"],
             "Pre-pruning stops growth early instead of cutting back later."),
            ("What is post-pruning?",
             "Grow the full tree, then remove weak subtrees",
             ["Stop before the first split", "Shuffle the data", "Train many trees"],
             "Cost-complexity pruning is a common post-pruning method."),
            ("A fully grown tree gets 100% training accuracy but poor test accuracy. This is…",
             "Overfitting",
             ["Underfitting", "A perfect model", "Always data leakage"],
             "The gap between training and test performance is the key sign."),
            ("In cost-complexity pruning, a larger α leads to…",
             "A smaller, simpler tree",
             ["A deeper tree", "No change", "More features"],
             "α penalizes every leaf, so higher α removes more of them."),
        ],
        "Feature Importance": [
            ("Impurity-based feature importance measures…",
             "The total impurity reduction from splits on that feature",
             ["How often the feature is missing", "The feature's value range", "Correlation with the row ID"],
             "It adds up the gain every time the feature is used to split."),
            ("A known weakness of impurity-based importance is…",
             "Bias toward features with many unique values",
             ["It can't be computed for trees", "It is always zero", "It only works for regression"],
             "High-cardinality features offer more possible split points."),
            ("How does permutation importance work?",
             "Shuffle one feature's values and measure the drop in performance",
             ["Delete rows at random", "Double the feature's values", "Sort the feature"],
             "If shuffling hurts the score, the model relied on that feature."),
            ("A feature never used in any split has importance…",
             "0",
             ["1", "A random value", "The highest of all features"],
             "It never reduced impurity, so it earns no credit."),
            ("With two highly correlated features, their importances may…",
             "Be split between them, so each looks less important",
             ["Both double", "Make the tree fail to train", "Always become negative"],
             "The tree can use either one, spreading the credit."),
        ],
    },
    "l5": {
        "Margins": [
            ("An SVM looks for the hyperplane that…",
             "Maximizes the margin between the classes",
             ["Passes through the most points", "Uses zero support vectors", "Maximizes the number of features"],
             "The widest gap between classes tends to generalize best."),
            ("For the margin planes w·x + b = ±1, the margin width is…",
             "2 / ‖w‖",
             ["‖w‖", "1 / 2", "‖w‖²"],
             "The distance between the two planes is 2/‖w‖, so we minimize ‖w‖."),
            ("A soft-margin SVM allows…",
             "Some points inside the margin or misclassified, penalized by C",
             ["No errors at all", "An infinite margin", "Removing features"],
             "Slack variables make SVMs work on data that isn't perfectly separable."),
            ("A very large C means the SVM…",
             "Penalizes errors heavily, giving a narrower margin",
             ["Gets a wider margin", "Ignores errors", "Switches to a linear kernel"],
             "High C prioritizes fitting the training data, which risks overfitting."),
            ("Why does a large margin help?",
             "It tends to generalize better to unseen data",
             ["It only makes training slower", "It guarantees 100% test accuracy", "It reduces the number of features"],
             "A wide buffer makes the boundary less sensitive to small changes in the data."),
        ],
        "Kernels": [
            ("What does the kernel trick allow an SVM to do?",
             "Compute inner products in a high-dimensional space without mapping explicitly",
             ["Shrink the dataset", "Skip training", "Keep the boundary linear in input space"],
             "k(x, x') = φ(x)·φ(x') is computed directly from x and x'."),
            ("What is the RBF (Gaussian) kernel?",
             "exp(−γ‖x − x'‖²)",
             ["x · x'", "(x · x') + 1", "max(0, x)"],
             "Similarity decays with squared distance between points."),
            ("A very large γ in the RBF kernel tends to give…",
             "A very wiggly boundary that can overfit",
             ["A straight line", "Guaranteed underfitting", "A model that ignores the data"],
             "Each point's influence becomes very local."),
            ("A degree-2 polynomial kernel captures…",
             "Pairwise feature interactions like x₁x₂ and x₁²",
             ["Only linear terms", "Only pixel values", "Only categorical data"],
             "(x·x' + c)² expands into all second-order terms."),
            ("For high-dimensional, nearly separable data such as text, a good first choice is…",
             "A linear kernel",
             ["RBF with a huge γ", "No kernel is possible", "A sigmoid output layer"],
             "With many features the classes are often already linearly separable."),
        ],
        "Support Vectors": [
            ("What are support vectors?",
             "Training points on or inside the margin that define the boundary",
             ["All training points", "The points farthest from the boundary", "The test points"],
             "Only these points constrain where the hyperplane sits."),
            ("Removing a training point that is not a support vector will…",
             "Leave the decision boundary unchanged",
             ["Always change the boundary", "Flip the labels", "Double the margin"],
             "Points outside the margin have zero weight (α = 0)."),
            ("An SVM's prediction depends on…",
             "Only the support vectors",
             ["All training points equally", "Only the first training point", "The labels of the test points"],
             "f(x) = Σ αᵢyᵢk(xᵢ, x) + b, and αᵢ = 0 for non-support vectors."),
            ("A very large number of support vectors often indicates…",
             "Overlapping classes or an overly flexible model",
             ["Perfect separation", "The model was never trained", "A linear kernel error"],
             "Many points end up inside or on the wrong side of the margin."),
            ("In the dual formulation, points with α > 0 are…",
             "The support vectors",
             ["Outliers that were removed", "The test points", "The features"],
             "Non-zero multipliers mark the points that shape the boundary."),
        ],
    },
    "l6": {
        "Centroids": [
            ("What is a centroid in k-means?",
             "The mean of the points assigned to a cluster",
             ["The median of the whole dataset", "The farthest point in the cluster", "A new random point each step"],
             "Each cluster is represented by its center of mass."),
            ("In the update step, each centroid is recomputed as…",
             "The average of its assigned points",
             ["A random point", "The largest point", "A merge of two clusters"],
             "The mean minimizes squared distance to the cluster's points."),
            ("Which initialization usually improves k-means results?",
             "k-means++, which spreads the initial centroids apart",
             ["Putting every centroid at the origin", "Starting all centroids on the same point", "Taking the first k rows in order"],
             "Well-spread starting points avoid poor local minima."),
            ("What objective does k-means minimize?",
             "The within-cluster sum of squared distances",
             ["The distance between points in the same cluster, maximized", "The number of clusters", "The number of labels"],
             "This quantity is also called inertia."),
            ("What is the centroid of (1, 2), (3, 4) and (5, 6)?",
             "(3, 4)",
             ["(9, 12)", "(1, 2)", "(5, 6)"],
             "Average x = 9/3 = 3 and average y = 12/3 = 4."),
        ],
        "Assignment Step": [
            ("In the assignment step, each point is assigned to…",
             "The nearest centroid",
             ["The farthest centroid", "A random centroid", "The largest cluster"],
             "Usually measured with Euclidean distance."),
            ("When does k-means stop?",
             "When the assignments stop changing",
             ["After exactly one iteration", "When K equals the number of points", "When all points are in one cluster"],
             "At that point the centroids stop moving too."),
            ("k-means is guaranteed to converge to…",
             "A local minimum, not necessarily the global one",
             ["The global optimum", "Nothing: it never converges", "Zero loss"],
             "Different initializations can give different results."),
            ("Why should features be scaled before running k-means?",
             "Distances would be dominated by features with large ranges",
             ["k-means needs labels", "Scaling adds clusters", "Scaling is only needed for trees"],
             "A feature measured in thousands swamps one measured in fractions."),
            ("k-means assignments are…",
             "Hard: each point belongs to exactly one cluster",
             ["Probabilities over all clusters", "Empty", "Always split across two clusters"],
             "Soft assignments are used by methods like Gaussian mixtures instead."),
        ],
        "Choosing K": [
            ("How does the elbow method choose K?",
             "Plot inertia against K and pick where improvements level off",
             ["Pick the K with the highest inertia", "Always use K = 2", "Set K to the number of features"],
             "After the elbow, extra clusters add little."),
            ("Why not just choose the K that minimizes inertia?",
             "Inertia keeps falling as K grows and reaches 0 when K = N",
             ["Inertia increases with K", "Inertia never changes", "Inertia is undefined"],
             "One point per cluster gives zero inertia but a useless clustering."),
            ("A silhouette score near 1 means…",
             "Points fit their own cluster well and are far from others",
             ["The clustering is poor", "The labels are random", "The clusters overlap heavily"],
             "Silhouette compares cohesion to separation."),
            ("How can domain knowledge set K?",
             "For example, a fixed number of T-shirt sizes to produce",
             ["K must always be 3", "K is learned by gradient descent", "K always equals the number of samples"],
             "Sometimes the business problem dictates the number of groups."),
            ("k-means struggles most with…",
             "Non-spherical or very differently sized clusters",
             ["Numeric data", "2-D data", "Small values of K"],
             "Nearest-centroid assignment assumes compact, round clusters."),
        ],
    },
    "l7": {
        "Layers": [
            ("What is a hidden layer?",
             "A layer between input and output whose values aren't directly observed",
             ["A layer that hides data from users", "The output layer", "The loss function"],
             "Hidden layers learn intermediate representations."),
            ("A dense layer with 4 inputs and 3 neurons (with biases) has how many parameters?",
             "15",
             ["12", "7", "3"],
             "4 × 3 weights + 3 biases = 15."),
            ("For 10-class classification, the output layer typically has…",
             "10 neurons with softmax",
             ["1 neuron with ReLU", "2 neurons", "100 neurons"],
             "One neuron per class, with softmax turning scores into probabilities."),
            ("What do deeper networks make possible?",
             "Learning hierarchical features, from simple to complex",
             ["Never overfitting", "Training with no data", "Always training faster"],
             "Each layer builds on the features found by the previous one."),
            ("What does the universal approximation theorem say?",
             "One hidden layer with enough neurons can approximate any continuous function",
             ["You need at least 100 layers", "Networks only learn linear functions", "It only applies to images"],
             "It guarantees that such a network exists, not that training will easily find it."),
        ],
        "Forward Pass": [
            ("What is the forward pass?",
             "Computing outputs layer by layer from the inputs",
             ["Updating the weights", "Computing gradients backward", "Shuffling the data"],
             "Data flows from the input layer to the output."),
            ("Each neuron computes…",
             "activation(w·x + b)",
             ["Only the maximum of its inputs", "A sort of its inputs", "w + x"],
             "A weighted sum followed by a nonlinearity."),
            ("What is the matrix form of one layer?",
             "a = f(Wx + b)",
             ["a = W + x", "a = x / W", "a = f(W) · f(x)"],
             "A whole layer is one matrix multiply plus bias, then the activation."),
            ("At inference time in production, a network runs…",
             "Only the forward pass",
             ["Forward and backward passes", "Only the backward pass", "Neither"],
             "Gradients are only needed during training."),
            ("A ReLU neuron whose w·x + b = −3 outputs…",
             "0",
             ["−3", "3", "1"],
             "ReLU(z) = max(0, z)."),
        ],
        "Nonlinearity": [
            ("Why do neural networks need nonlinear activations?",
             "Without them, stacked layers collapse into one linear transformation",
             ["They make training faster", "They reduce the parameter count", "Only the input layer needs them"],
             "W₂(W₁x) = (W₂W₁)x is still linear."),
            ("What is ReLU(x)?",
             "max(0, x)",
             ["1 / (1 + e^(−x))", "x²", "tanh(x)"],
             "It passes positives through and zeroes negatives."),
            ("What is the output range of tanh?",
             "−1 to 1",
             ["0 to 1", "0 to infinity", "Any real number"],
             "tanh is a zero-centered, rescaled sigmoid."),
            ("An advantage of ReLU over sigmoid in deep networks is…",
             "It doesn't saturate for positive inputs, reducing vanishing gradients",
             ["It outputs probabilities", "It is differentiable everywhere", "Its output is bounded"],
             "The gradient is 1 for any positive input."),
            ("What is the 'dying ReLU' problem?",
             "Neurons get stuck outputting 0 and receive no gradient",
             ["Outputs become infinite", "Training data gets deleted", "Neurons duplicate themselves"],
             "If the input is always negative, the gradient is always 0."),
        ],
    },
    "l8": {
        "Chain Rule": [
            ("By the chain rule, for y = f(g(x)), dy/dx equals…",
             "f'(g(x)) · g'(x)",
             ["f'(x) + g'(x)", "f(x) · g(x)", "f'(g'(x))"],
             "Multiply the outer derivative by the inner derivative."),
            ("Backpropagation applies the chain rule to…",
             "Compute the loss gradient for every weight, from output back to input",
             ["Run the network from input to output only", "Generate data labels", "Choose the learning rate"],
             "Gradients flow backward through each layer."),
            ("For y = (3x + 1)², what is dy/dx at x = 1?",
             "24",
             ["16", "12", "8"],
             "dy/dx = 2(3x + 1)·3 = 2·4·3 = 24."),
            ("Why compute gradients backward rather than one weight at a time?",
             "It reuses intermediate gradients, so all gradients cost about one extra pass",
             ["Forward gradients are impossible", "Any order is equally fast", "It needs no memory"],
             "Reverse-mode differentiation shares work across all parameters."),
            ("Frameworks like PyTorch automate this with…",
             "Automatic differentiation (autograd)",
             ["Derivatives the user writes by hand", "Only finite differences", "SQL queries"],
             "They record operations and replay the chain rule in reverse."),
        ],
        "Gradients": [
            ("The gradient of the loss with respect to a weight tells you…",
             "How the loss changes if that weight is nudged",
             ["The weight's final value", "The number of layers", "The model's accuracy"],
             "Its sign and size tell you which way to update and how much."),
            ("What is the standard weight update?",
             "w ← w − η · ∂L/∂w",
             ["w ← w + η · ∂L/∂w", "w ← ∂L/∂w", "w ← η"],
             "Step opposite to the gradient to decrease the loss."),
            ("Gradient checking compares…",
             "Backprop gradients to numerical finite-difference estimates",
             ["Gradients to the labels", "Gradients to the learning rate", "Gradients to test accuracy"],
             "It catches bugs in hand-written backward passes."),
            ("A common fix for exploding gradients is…",
             "Gradient clipping",
             ["A larger learning rate", "Removing the biases", "More epochs"],
             "Clipping caps the gradient norm before each update."),
            ("A mini-batch gradient is…",
             "The average gradient over a small batch of examples",
             ["The gradient of a single weight", "The sum of the labels", "Only the largest gradient"],
             "It balances the noise of SGD against the cost of full-batch gradients."),
        ],
        "Vanishing Gradients": [
            ("What are vanishing gradients?",
             "Gradients shrink toward zero in early layers, so those layers learn very slowly",
             ["Gradients become huge", "Weights disappear from memory", "Training data is lost"],
             "Early layers receive almost no learning signal."),
            ("Which activation contributes most to vanishing gradients?",
             "Sigmoid",
             ["ReLU", "Identity", "Leaky ReLU"],
             "Its derivative is at most 0.25, and many such factors multiply together."),
            ("Which architectural technique helps with vanishing gradients?",
             "Residual (skip) connections",
             ["Stacking more sigmoid layers", "Removing normalization", "Using a smaller learning rate only"],
             "Skip paths let gradients flow directly to earlier layers."),
            ("Which weight initializations are designed to keep signal variance stable?",
             "Xavier / He initialization",
             ["All zeros", "All ones", "Very large random values"],
             "They scale initial weights by layer width."),
            ("Why does depth make vanishing gradients worse?",
             "The gradient is a product of per-layer factors; if each is below 1 it shrinks exponentially",
             ["Deep networks have fewer weights", "Depth adds more labels", "Depth and gradients are unrelated"],
             "For example, 0.25¹⁰ ≈ 0.000001."),
        ],
    },
    "l9": {
        "Convolution": [
            ("What does a convolutional layer do?",
             "Slides small learnable filters over the input, computing local weighted sums",
             ["Connects every pixel to every neuron", "Sorts the pixels", "Compresses the image file"],
             "Each filter detects one local pattern everywhere in the image."),
            ("A 32×32 input with a 5×5 filter, stride 1 and no padding gives an output of…",
             "28×28",
             ["32×32", "27×27", "30×30"],
             "32 − 5 + 1 = 28."),
            ("Why do CNNs need far fewer parameters than dense layers on images?",
             "Weight sharing: the same filter is reused at every position",
             ["They have no weights", "They ignore color", "They use fewer images"],
             "One small filter replaces millions of pixel-to-neuron weights."),
            ("What is 'same' padding for?",
             "Keeping the output's spatial size equal to the input's",
             ["Doubling the size", "Removing the borders", "Adding channels"],
             "Zeros are added around the border so edge pixels are covered."),
            ("How many weights (excluding bias) does one 3×3 filter on an RGB input have?",
             "27",
             ["9", "3", "12"],
             "3 × 3 × 3 channels = 27."),
        ],
        "Pooling": [
            ("What does max pooling do?",
             "Takes the maximum value in each window",
             ["Averages the whole image", "Takes the minimum value", "Sums all channels"],
             "It keeps the strongest activation in each region."),
            ("2×2 pooling with stride 2 on a 16×16 feature map gives…",
             "8×8",
             ["16×16", "4×4", "14×14"],
             "Each dimension is halved."),
            ("What is the main benefit of pooling?",
             "Smaller spatial size and a little translation invariance",
             ["More parameters", "Higher resolution", "Learning colors"],
             "Small shifts in the input barely change the pooled output."),
            ("How many learnable parameters does a max-pooling layer have?",
             "None",
             ["One per pixel", "9", "It depends on the number of classes"],
             "Pooling is a fixed operation."),
            ("What does global average pooling do?",
             "Averages each feature map down to a single number",
             ["Takes the maximum across the whole dataset", "Pools across the batch", "Removes every channel"],
             "It often replaces large dense layers at the end of a CNN."),
        ],
        "Feature Maps": [
            ("What is a feature map?",
             "The output of one filter, showing where its pattern appears",
             ["A map of the dataset", "A list of labels", "Image metadata"],
             "High values mark locations where the filter's pattern was found."),
            ("A convolutional layer with 64 filters produces…",
             "64 feature maps (channels)",
             ["1 feature map", "32 feature maps", "128 feature maps"],
             "Each filter produces its own map."),
            ("What do early CNN layers typically detect?",
             "Simple patterns like edges and colors",
             ["Whole objects", "Class labels", "Text captions"],
             "Early filters see only small patches."),
            ("What do deeper CNN layers typically detect?",
             "More abstract features such as object parts",
             ["Raw pixels", "Only edges", "Nothing useful"],
             "They combine lower-level features over larger regions."),
            ("What is a receptive field?",
             "The region of the input image that affects a given feature value",
             ["The number of filters", "The batch size", "The learning rate"],
             "It grows with depth, stride and pooling."),
        ],
    },
    "l10": {
        "Sequences": [
            ("RNNs are designed for…",
             "Sequential data like text, audio and time series",
             ["Unordered sets", "Only static images", "Only tabular data"],
             "They process inputs one step at a time, in order."),
            ("A key property of RNNs is that…",
             "The same weights are applied at every time step",
             ["Each step gets new weights", "They have no weights", "They only work on sequences of length 10"],
             "Weight sharing across time handles sequences of any length."),
            ("Which is a many-to-one sequence task?",
             "Classifying the sentiment of a sentence",
             ["Machine translation", "Generating an image from noise", "Tagging every word with its part of speech"],
             "Many input steps produce a single output."),
            ("RNNs are trained with…",
             "Backpropagation through time (BPTT)",
             ["k-means", "Decision tree pruning", "Closed-form least squares"],
             "The network is unrolled over time and backprop is applied to it."),
            ("Which is a sequence-to-sequence task?",
             "Machine translation",
             ["Classifying a single image", "Predicting a house price from features", "Clustering customers"],
             "An input sequence maps to an output sequence of different length."),
        ],
        "Hidden State": [
            ("What is the hidden state in an RNN?",
             "A memory summarizing what the network has seen so far",
             ["The final label", "The learning rate", "The embedding table"],
             "It carries information from earlier steps forward."),
            ("What is the vanilla RNN hidden-state update?",
             "hₜ = tanh(W_h hₜ₋₁ + W_x xₜ + b)",
             ["hₜ = xₜ", "hₜ = hₜ₋₁", "hₜ = W xₜ only"],
             "It mixes the previous state with the current input."),
            ("The initial hidden state h₀ is commonly set to…",
             "Zeros",
             ["The label", "Very large random values", "The last test output"],
             "Starting from zero is simple and works well."),
            ("Why do vanilla RNNs struggle with long-term dependencies?",
             "Gradients vanish or explode over many time steps",
             ["They can't process text", "They have no hidden state", "They have too few parameters"],
             "Repeatedly multiplying by the same matrix shrinks or blows up the signal."),
            ("What is a bidirectional RNN?",
             "It reads the sequence forward and backward and combines both states",
             ["Two stacked layers going the same way", "It reads only half the sequence", "It loops forever"],
             "Each position then sees both past and future context."),
        ],
        "LSTM / GRU": [
            ("Which gates does an LSTM have?",
             "Input, forget and output gates",
             ["Only reset and update gates", "Query, key and value gates", "Pooling gates"],
             "Reset and update gates belong to the GRU."),
            ("What does the forget gate do?",
             "Decides how much of the previous cell state to keep",
             ["Deletes training data", "Picks the learning rate", "Outputs the label"],
             "Values near 0 erase the old memory; values near 1 keep it."),
            ("Why do LSTMs handle long sequences better than vanilla RNNs?",
             "The additive cell-state path lets gradients flow across many steps",
             ["They have no weights", "They ignore earlier inputs", "They use convolutions"],
             "The cell state is updated by addition, not repeated squashing."),
            ("How does a GRU differ from an LSTM?",
             "It merges gates into update and reset gates and has no separate cell state",
             ["It has more gates than an LSTM", "It can't learn sequences", "They are identical"],
             "It has fewer parameters and often performs similarly."),
            ("Gate values in LSTMs and GRUs come from…",
             "A sigmoid, giving values between 0 and 1",
             ["ReLU, which is unbounded", "Softmax over the vocabulary", "A step function"],
             "A 0–1 value acts like a soft on/off switch."),
        ],
    },
}
