"""Programming city quizzes."""

LEVELS = {
    "l1": {
        "Primitives": [
            ("Which of these is a primitive type in JavaScript?",
             "number",
             ["Array", "Object", "Map"],
             "Arrays, objects and maps are all reference types."),
            ("In Python, what does 7 // 2 evaluate to?",
             "3",
             ["3.5", "4", "1"],
             "// is floor division."),
            ("In JavaScript, what does 0.1 + 0.2 === 0.3 return?",
             "false, because of floating-point rounding",
             ["true", "It throws an error", "undefined"],
             "0.1 + 0.2 is 0.30000000000000004 in binary floating point."),
            ("What values can a boolean hold?",
             "true or false",
             ["Any integer", "Any text", "Lists of values"],
             "Booleans represent logical truth values."),
            ("What is the maximum value of a 32-bit signed integer?",
             "2,147,483,647",
             ["4,294,967,295", "65,535", "1,000,000"],
             "2³¹ − 1; one bit is used for the sign."),
        ],
        "References": [
            ("In Python: a = [1, 2]; b = a; b.append(3); print(a). What is printed?",
             "[1, 2, 3]",
             ["[1, 2]", "An error", "[3]"],
             "a and b refer to the same list object."),
            ("What does a reference variable store?",
             "A pointer to the object rather than the object itself",
             ["A full copy of the object", "The name of the type", "Nothing"],
             "Assigning it copies the reference, not the data."),
            ("How does a shallow copy differ from a deep copy?",
             "A shallow copy duplicates the outer container but shares nested objects",
             ["They are identical", "A shallow copy duplicates everything", "A deep copy shares nested objects"],
             "Changing a nested list inside a shallow copy affects the original."),
            ("Strings in JavaScript are…",
             "Immutable",
             ["Mutable in place", "References to arrays", "Numbers underneath"],
             "String methods return new strings instead of changing the original."),
            ("In Python, what does 'a is b' check?",
             "Whether a and b are the same object",
             ["Whether their values are equal", "Whether they have the same type", "Whether they have the same length"],
             "== compares values; 'is' compares identity."),
        ],
        "Type Systems": [
            ("What does static typing mean?",
             "Types are checked at compile time",
             ["Types are only checked at runtime", "Types are never checked", "The user checks the types"],
             "Errors are caught before the program runs."),
            ("Which language is dynamically typed?",
             "Python",
             ["Java", "Rust", "C"],
             "Python checks types while the program runs."),
            ("In JavaScript, what is \"5\" + 1?",
             "\"51\"",
             ["6", "An error", "NaN"],
             "With a string involved, + concatenates."),
            ("What is type inference?",
             "The compiler works out types without explicit annotations",
             ["Guessing types at random", "Always writing every type by hand", "A runtime crash"],
             "For example, TypeScript infers number from let x = 5."),
            ("What is a sign of strong typing?",
             "No implicit conversions between unrelated types, e.g. Python's \"5\" + 1 raises TypeError",
             ["Variables take up a lot of memory", "The program runs fast", "There are no types"],
             "Strong vs weak is about implicit conversion; static vs dynamic is about when checks happen."),
        ],
    },
    "l2": {
        "Branching": [
            ("With x = 7: if x > 10: 'big' / elif x > 5: 'mid' / else: 'small'. What is printed?",
             "mid",
             ["big", "small", "Nothing"],
             "7 > 10 is false and 7 > 5 is true."),
            ("In false && f(), is f() called?",
             "No, because of short-circuit evaluation",
             ["Yes, always", "It throws an error", "It is called twice"],
             "&& stops as soon as the result is known."),
            ("When is a switch/match statement a good fit?",
             "Choosing among many discrete values of one expression",
             ["Writing loops", "Handling errors", "Converting types"],
             "It is clearer than a long chain of else-ifs."),
            ("What does x = cond ? a : b assign?",
             "a if cond is true, otherwise b",
             ["Both a and b", "The value of cond", "Always b"],
             "The ternary operator is a compact if/else expression."),
            ("What happens if you forget 'break' in a C switch case?",
             "Execution falls through into the next case",
             ["It always fails to compile", "The program exits", "Every case is skipped"],
             "Fall-through is a classic source of bugs."),
        ],
        "Loops": [
            ("What does 'for i in range(3): print(i)' print?",
             "0 1 2",
             ["1 2 3", "0 1 2 3", "3"],
             "range(3) starts at 0 and stops before 3."),
            ("How long does a while loop run?",
             "As long as its condition stays true",
             ["Exactly once", "A fixed number of times", "Until an error occurs"],
             "The condition is checked before each iteration."),
            ("What does 'continue' do inside a loop?",
             "Skips to the next iteration",
             ["Exits the loop", "Restarts the program", "Pauses execution"],
             "'break' is the one that exits the loop."),
            ("What does a do-while loop guarantee?",
             "The body runs at least once",
             ["The body never runs", "The body runs exactly twice", "The condition is checked first"],
             "The condition is checked after the body."),
            ("A common cause of an infinite loop is…",
             "The condition never becomes false, e.g. the counter is never updated",
             ["Using break", "Using a for loop", "Having too few variables"],
             "Always make sure the loop makes progress toward ending."),
        ],
        "Recursion Basics": [
            ("What is the base case of a recursive function?",
             "The condition where it stops calling itself",
             ["The first call", "The largest input", "The loop variable"],
             "Every recursive function needs one."),
            ("What happens when a recursive function has no base case?",
             "Infinite recursion, ending in a stack overflow",
             ["It returns 0", "It runs faster", "It fails to compile"],
             "Every call adds a stack frame until memory runs out."),
            ("What does a recursive factorial(4) return?",
             "24",
             ["10", "16", "4"],
             "4 × 3 × 2 × 1 = 24."),
            ("Each recursive call gets…",
             "Its own stack frame with its own local variables",
             ["Shared local variables", "No memory", "Only global variables"],
             "That is how each call keeps its own n."),
            ("Why is naive recursive Fibonacci slow?",
             "It recomputes the same subproblems an exponential number of times",
             ["It uses loops", "It makes too few calls", "It uses memoization"],
             "Memoization or iteration makes it linear."),
        ],
    },
    "l3": {
        "Parameters": [
            ("What is the difference between a parameter and an argument?",
             "A parameter is the name in the definition; an argument is the value passed in",
             ["They are the same thing", "It's the other way around", "Arguments are types"],
             "def f(x): x is a parameter; f(5): 5 is an argument."),
            ("In def greet(name=\"World\"), when is the default used?",
             "When the caller leaves out that argument",
             ["Always", "Never; it raises an error", "Only for global variables"],
             "greet() uses \"World\"; greet(\"Ana\") uses \"Ana\"."),
            ("What is the pitfall in Python's def add(x, items=[])?",
             "The same list is shared across every call",
             ["A new list is created on every call", "It raises an error", "The list is immutable"],
             "Defaults are evaluated once; use items=None instead."),
            ("What does *args do in a Python function?",
             "Collects extra positional arguments into a tuple",
             ["Collects keyword arguments into a dict", "Creates a pointer", "Makes the first argument required"],
             "**kwargs collects keyword arguments."),
            ("What are keyword arguments?",
             "Arguments passed by name, so order doesn't matter, e.g. f(b=2, a=1)",
             ["Arguments that must be in order", "Only numbers", "Global variables"],
             "They make calls clearer and more flexible."),
        ],
        "Scope": [
            ("Where can a local variable be used?",
             "Only inside the function where it is defined",
             ["Everywhere", "Only inside loops", "Forever after it is created"],
             "It disappears when the function returns."),
            ("x = 5; def f(): x = 10; then f(); print(x). What is printed?",
             "5",
             ["10", "An error", "None"],
             "The x inside f is a new local variable."),
            ("How does let differ from var in JavaScript?",
             "let is block-scoped; var is function-scoped",
             ["They are the same", "var is block-scoped", "let is always global"],
             "let stays inside its { } block."),
            ("What does Python's 'global' keyword do?",
             "Lets a function assign to a module-level variable",
             ["Creates a new local variable", "Deletes the variable", "Imports a module"],
             "Without it, assignment creates a local variable."),
            ("What does LEGB stand for in Python name lookup?",
             "Local, Enclosing, Global, Built-in",
             ["Loop, Else, Global, Break", "List, Enum, Generator, Bytes", "Left, Edge, Grid, Block"],
             "Python searches scopes in that order."),
        ],
        "Closures": [
            ("What is a closure?",
             "A function that remembers variables from its enclosing scope after that scope returns",
             ["Closing a file", "The end of a loop", "A class destructor"],
             "The inner function keeps its environment alive."),
            ("make_counter() returns inc, which does 'nonlocal c; c += 1; return c'. What does the second call to counter() return?",
             "2",
             ["1", "0", "An error"],
             "c lives on in the closure between calls."),
            ("What does 'nonlocal' do in Python?",
             "Assigns to a variable in the enclosing function's scope",
             ["Makes the variable global", "Makes it local", "Deletes it"],
             "It is needed to rebind a variable captured by a closure."),
            ("A common use of closures is…",
             "Function factories and callbacks that keep private state",
             ["Compiling code", "Only sorting", "Freeing memory"],
             "They are a lightweight alternative to small classes."),
            ("for (var i = 0; i < 3; i++) setTimeout(() => console.log(i)). What is logged?",
             "3, 3, 3",
             ["0, 1, 2", "1, 2, 3", "undefined three times"],
             "var is shared by every callback; with let you'd get 0, 1, 2."),
        ],
    },
    "l4": {
        "Arrays & Lists": [
            ("What is the time complexity of accessing an array element by index?",
             "O(1)",
             ["O(n)", "O(log n)", "O(n²)"],
             "The address is computed directly from the index."),
            ("Inserting at the start of a dynamic array costs…",
             "O(n), because every element must shift",
             ["O(1)", "O(log n)", "O(n²)"],
             "Use a deque or linked list for fast front inserts."),
            ("What is the advantage of a linked list?",
             "O(1) insertion or removal when you already have the node",
             ["O(1) random access", "It always uses less memory", "It is always sorted"],
             "Only the neighboring pointers need to change."),
            ("What is the amortized cost of appending to a dynamic array?",
             "O(1)",
             ["O(n)", "O(log n)", "O(n log n)"],
             "Occasional resizes are spread across many cheap appends."),
            ("In Python, what does list[-1] return?",
             "The last element",
             ["The first element", "An error", "The second element"],
             "Negative indices count from the end."),
        ],
        "Hash Maps": [
            ("What is the average lookup time in a hash map?",
             "O(1)",
             ["O(n)", "O(log n)", "O(n²)"],
             "The hash points straight to a bucket."),
            ("What is a hash collision?",
             "Two different keys hashing to the same bucket",
             ["A key being deleted", "The map being full", "Duplicate values"],
             "Collisions are normal and must be handled."),
            ("How do hash maps handle collisions?",
             "Chaining (a list per bucket) or open addressing",
             ["Deleting the old key", "Crashing", "Sorting the keys"],
             "Both keep every key findable."),
            ("Why should hash-map keys be immutable?",
             "If a key's hash changed after insertion, it could no longer be found",
             ["It makes printing faster", "It saves memory", "The CPU requires it"],
             "That is why Python won't let you use a list as a dict key."),
            ("Which task is a hash map ideal for?",
             "Counting word frequencies",
             ["Keeping items sorted by default", "A FIFO queue", "Matrix multiplication"],
             "Word → count lookups and updates are O(1)."),
        ],
        "Trees": [
            ("What is the binary search tree property?",
             "Left subtree < node < right subtree",
             ["Left subtree > right subtree", "Values are in random order", "All values are equal"],
             "It lets you discard half the tree at each step."),
            ("What is the search time in a balanced BST?",
             "O(log n)",
             ["O(1)", "O(n)", "O(n²)"],
             "The height stays around log₂ n."),
            ("An in-order traversal of a BST visits values in…",
             "Sorted order",
             ["Reverse insertion order", "Random order", "Level order"],
             "Left, node, right follows the BST ordering."),
            ("What is a leaf node?",
             "A node with no children",
             ["The root", "A node with two children", "Any parent node"],
             "Leaves are at the bottom of the tree."),
            ("What happens if sorted data is inserted into an unbalanced BST?",
             "It degrades into a linked list with O(n) search",
             ["It stays O(log n)", "Search becomes O(1)", "It crashes"],
             "Self-balancing trees such as AVL and red-black trees prevent this."),
        ],
    },
    "l5": {
        "Sorting": [
            ("What is merge sort's time complexity?",
             "O(n log n) in every case",
             ["O(n²)", "O(n)", "O(log n)"],
             "It splits log n times and merges in O(n) per level."),
            ("What is quicksort's worst case?",
             "O(n²), with consistently bad pivots",
             ["O(n log n)", "O(n)", "O(1)"],
             "Random or median-of-three pivots make this rare."),
            ("What is a stable sort?",
             "One that keeps equal elements in their original relative order",
             ["The fastest sort", "Any in-place sort", "A random sort"],
             "Stability matters when sorting by several keys."),
            ("Which algorithm is best for small, nearly sorted data?",
             "Insertion sort",
             ["Quicksort with a first-element pivot", "Selection sort", "Bogosort"],
             "It runs in close to O(n) when few elements are out of place."),
            ("What is the lower bound for comparison-based sorting?",
             "Ω(n log n)",
             ["Ω(n)", "Ω(1)", "Ω(n²)"],
             "There are n! orderings, and each comparison gives one bit of information."),
        ],
        "Searching": [
            ("What does binary search require?",
             "Sorted data",
             ["Unsorted data", "A linked list", "A hash map"],
             "It relies on order to discard half the range."),
            ("What is binary search's time complexity?",
             "O(log n)",
             ["O(n)", "O(1)", "O(n log n)"],
             "The range halves with every step."),
            ("In the worst case, linear search over n unsorted items makes…",
             "n comparisons",
             ["log n comparisons", "1 comparison", "n² comparisons"],
             "The target might be last, or missing."),
            ("About how many steps does binary search need for 1,000,000 items?",
             "20",
             ["1,000", "500,000", "100"],
             "2²⁰ ≈ 1,048,576."),
            ("What is a common binary search bug?",
             "Off-by-one errors or overflow when computing mid",
             ["Searching a sorted array", "Having too few elements", "Using a loop"],
             "Use lo + (hi − lo) / 2 and check the bounds carefully."),
        ],
        "Big-O": [
            ("What does Big-O notation describe?",
             "How time or space grows with input size (an upper bound)",
             ["The exact running time in seconds", "The number of lines of code", "The memory brand"],
             "It ignores constants and focuses on growth."),
            ("Two nested loops, each over n items, are…",
             "O(n²)",
             ["O(n)", "O(log n)", "O(2n)"],
             "n iterations times n iterations."),
            ("What does O(3n + 100) simplify to?",
             "O(n)",
             ["O(3n + 100)", "O(1)", "O(n²)"],
             "Constant factors and lower-order terms are dropped."),
            ("Which grows fastest for large n?",
             "O(2ⁿ)",
             ["O(n²)", "O(n log n)", "O(n³)"],
             "Exponential growth eventually beats any polynomial."),
            ("A loop over n items doing a hash-set lookup each time is…",
             "O(n) on average",
             ["O(n²)", "O(log n)", "O(1)"],
             "n iterations × O(1) per lookup."),
        ],
    },
    "l6": {
        "Classes": [
            ("What is the difference between a class and an object?",
             "A class is a blueprint; an object is an instance of it",
             ["They are the same thing", "It's the other way around", "Objects are functions"],
             "Many objects can be created from one class."),
            ("What does a constructor such as __init__ do?",
             "Initializes a new object's state",
             ["Deletes the object", "Prints the object", "Compiles the class"],
             "It runs automatically when an object is created."),
            ("What is encapsulation?",
             "Bundling data with its methods and restricting direct access to internal state",
             ["Inheritance", "Zipping files", "Writing loops"],
             "Callers use the public methods, not the internals."),
            ("What do 'self' / 'this' refer to?",
             "The current instance",
             ["The parent class", "The global scope", "The module"],
             "They give a method access to its own object's data."),
            ("What is a static or class method?",
             "A method that belongs to the class and can be called without an instance",
             ["A method that needs an instance", "A method that is always private", "The constructor"],
             "For example, Math.max() in JavaScript."),
        ],
        "Inheritance": [
            ("What is inheritance?",
             "A subclass reusing and extending a superclass's behavior",
             ["Copying files", "A memory leak", "Interfaces only"],
             "class Dog(Animal) inherits Animal's methods."),
            ("What is method overriding?",
             "A subclass providing its own version of a superclass method",
             ["Same method name with different parameters", "Deleting a method", "Making a method private"],
             "Same name with different parameters is overloading."),
            ("What does super() do?",
             "Calls the parent class's implementation",
             ["Creates a new class", "Accesses globals", "Calls a sibling class"],
             "It is often used to extend a parent constructor."),
            ("What does 'composition over inheritance' advise?",
             "Build classes from has-a parts to avoid tight coupling",
             ["Never use objects", "Always build deep class hierarchies", "Avoid composition because it's slow"],
             "Composition is usually more flexible than deep inheritance trees."),
            ("What is polymorphism?",
             "One interface with different behavior per type, e.g. shape.area()",
             ["Having many variables", "Splitting code across files", "Using only one type"],
             "Callers don't need to know the concrete class."),
        ],
        "Interfaces": [
            ("What is an interface?",
             "A contract listing the methods a class must implement",
             ["A graphical user interface", "A concrete class with state", "A database"],
             "It says what a class does, not how."),
            ("Can a Java class implement multiple interfaces?",
             "Yes",
             ["No", "Only two", "Only if it is abstract"],
             "Java allows many interfaces but only one superclass."),
            ("How does an abstract class differ from a classic interface?",
             "An abstract class can hold state and implemented methods",
             ["They are identical", "Interfaces have constructors", "Abstract classes can be instantiated"],
             "Interfaces traditionally declare behavior only."),
            ("What is duck typing?",
             "If an object has the needed methods, it can be used, whatever its declared type",
             ["Strict naming rules", "Something about animals", "Only compile-time checks"],
             "'If it walks like a duck and quacks like a duck…'"),
            ("Why program to interfaces rather than implementations?",
             "You can swap implementations without changing the calling code",
             ["It makes the CPU faster", "It always means fewer files", "It removes the need for tests"],
             "It also makes mocking in tests easy."),
        ],
    },
    "l7": {
        "Exceptions": [
            ("What is try/except for?",
             "Catching and handling errors without crashing",
             ["Making code faster", "Writing loops", "Importing modules"],
             "It lets the program recover or fail gracefully."),
            ("When does a finally block run?",
             "Whether or not an exception occurred",
             ["Only when there is an error", "Never", "Only on success"],
             "It is ideal for cleanup like closing files."),
            ("Why is a bare 'except:' discouraged?",
             "It swallows every error, including real bugs and KeyboardInterrupt",
             ["It is a syntax error", "It is slower", "It is required"],
             "Catch specific exceptions instead."),
            ("How do you raise an exception in Python?",
             "raise ValueError(\"bad input\")",
             ["return error", "print(\"error\")", "exit(0)"],
             "raise stops normal flow and signals the problem to callers."),
            ("What happens to an exception that isn't caught?",
             "It propagates up the call stack to the callers",
             ["It disappears", "It restarts the function", "It stays where it happened"],
             "If nothing catches it, the program crashes with a traceback."),
        ],
        "Logging": [
            ("Why use logging instead of print?",
             "Levels, timestamps and configurable outputs that can be turned down",
             ["print is always faster", "print isn't supported", "The OS requires logging"],
             "Logs can go to files or services and be filtered by level."),
            ("Which standard logging level is the most severe?",
             "CRITICAL",
             ["DEBUG", "INFO", "WARNING"],
             "The order is DEBUG < INFO < WARNING < ERROR < CRITICAL."),
            ("What should never be logged?",
             "Passwords and secret tokens",
             ["Error messages", "Timestamps", "Request IDs"],
             "Logs are often widely readable and kept for a long time."),
            ("What is structured logging?",
             "Logging key–value or JSON fields that are easy to search",
             ["Logging in all caps", "Logging in a notebook", "Logging on paper"],
             "Tools can filter on fields like user_id."),
            ("What is the DEBUG level for?",
             "Detailed diagnostic information during development",
             ["Only crashes", "Messages shown to users", "Nothing"],
             "It is usually disabled in production."),
        ],
        "Debugging": [
            ("What is a breakpoint?",
             "A marker that pauses execution so you can inspect the program's state",
             ["A command that deletes a line", "A crash", "A compile step"],
             "Debuggers let you step through code line by line."),
            ("What is the first step in fixing a bug?",
             "Reproduce it reliably",
             ["Rewrite everything", "Ignore it", "Deploy the code"],
             "You can't confirm a fix without a reliable repro."),
            ("What is a stack trace?",
             "The sequence of function calls that led to an error",
             ["A list of variables", "The git history", "The CPU temperature"],
             "Read it from the error back to your code."),
            ("What is rubber-duck debugging?",
             "Explaining your code line by line until you spot the flaw",
             ["A toy", "Deleting code", "Making random changes"],
             "Saying assumptions out loud exposes wrong ones."),
            ("What does git bisect do?",
             "Binary-searches through commits to find the one that introduced a bug",
             ["Splits files in half", "Merges branches", "Deletes history"],
             "It finds the bad commit in O(log n) test runs."),
        ],
    },
    "l8": {
        "Unit Tests": [
            ("What is a unit test?",
             "A test of one small piece, such as a function or class, in isolation",
             ["A test of the entire system", "Manual UI testing", "Testing in production"],
             "Unit tests pinpoint exactly what broke."),
            ("What does assert do in a test?",
             "Checks a condition and fails the test if it is false",
             ["Prints a value", "Starts a loop", "Imports a module"],
             "For example, assert add(2, 2) == 4."),
            ("Good unit tests are…",
             "Fast, isolated and repeatable",
             ["Slow and order-dependent", "Random", "Dependent on the internet"],
             "Flaky tests erode trust in the whole test suite."),
            ("What does Arrange–Act–Assert mean?",
             "Set up the inputs, run the code, then check the result",
             ["Assert first, then arrange", "Only act", "Arrange the files alphabetically"],
             "It keeps tests readable and consistent."),
            ("What does code coverage measure?",
             "The percentage of code executed by the tests",
             ["Guaranteed correctness", "The number of tests", "The number of bugs found"],
             "High coverage doesn't prove the assertions are good."),
        ],
        "TDD": [
            ("What is the TDD cycle?",
             "Red, Green, Refactor",
             ["Write, Ship, Fix", "Plan, Code, Deploy", "Test, Delete, Retry"],
             "Failing test, passing code, then cleanup."),
            ("In TDD, what do you write first?",
             "A failing test",
             ["The feature implementation", "The deployment script", "The refactor"],
             "The test defines the behavior you want."),
            ("What happens in the refactor step?",
             "Improve the code's structure while keeping the tests passing",
             ["Add new features", "Delete the tests", "Rewrite the requirements"],
             "The tests act as a safety net."),
            ("What is a key benefit of TDD?",
             "It clarifies requirements and gives a safety net for future changes",
             ["It guarantees no bugs ever", "It removes the need for design", "It makes initial typing faster"],
             "Writing the test forces you to decide on behavior first."),
            ("What does 'Green' mean in TDD?",
             "Write the minimal code that makes the failing test pass",
             ["Write perfect code", "Delete the tests", "Write documentation"],
             "Keep it simple, then improve it in the refactor step."),
        ],
        "Mocks": [
            ("What is a mock?",
             "A fake object that stands in for a real dependency and records how it's called",
             ["A real database", "The production server", "A code comment"],
             "It isolates the code under test."),
            ("Why mock an external API in tests?",
             "Tests stay fast and deterministic, with no network needed",
             ["The API is unreachable forever", "To reduce coverage to 0", "It is required"],
             "Network calls are slow, flaky and may cost money."),
            ("How does a stub differ from a mock?",
             "A stub returns canned data; a mock also verifies how it was called",
             ["They are identical", "A stub verifies calls", "A mock is the real object"],
             "Mocks let you assert on interactions."),
            ("Which Python library provides mocking tools?",
             "unittest.mock",
             ["numpy", "requests", "matplotlib"],
             "It includes Mock, MagicMock and patch."),
            ("What is the risk of mocking too much?",
             "Tests pass while the real integration is broken",
             ["Tests become too slow", "Tests can't run", "Too many real calls are made"],
             "Keep some integration tests against real dependencies."),
        ],
    },
    "l9": {
        "Threads": [
            ("What is a thread?",
             "An independent path of execution inside a process, sharing its memory",
             ["A separate computer", "A file", "A variable"],
             "Threads in one process share the same address space."),
            ("What is a race condition?",
             "A result that depends on the timing of threads accessing shared data",
             ["A fast algorithm", "A compile error", "A sorting method"],
             "Two threads doing count += 1 can lose an update."),
            ("What is Python's GIL?",
             "A lock that lets only one thread run Python bytecode at a time in CPython",
             ["A GPU lock", "Something that speeds up CPU-bound threads", "A networking library"],
             "CPU-bound work needs processes to use multiple cores."),
            ("How do threads differ from processes?",
             "Threads share memory; processes have separate memory",
             ["It's the other way around", "They are identical", "Threads run on separate machines"],
             "Shared memory is fast but needs synchronization."),
            ("What is a good use of threads in Python?",
             "I/O-bound tasks, like downloading many files",
             ["CPU-heavy math", "Nothing", "Sorting a small list"],
             "The GIL is released while waiting on I/O."),
        ],
        "Async / Await": [
            ("What does await do?",
             "Pauses the coroutine until the awaited task finishes, letting others run",
             ["Blocks the whole program", "Creates a thread", "Ends the program"],
             "It yields control back to the event loop."),
            ("What does an async function in JavaScript return?",
             "A Promise",
             ["A string", "Always undefined", "A thread"],
             "Its return value is wrapped in a Promise."),
            ("What is async best suited for?",
             "Many concurrent I/O operations, such as network requests",
             ["Heavy CPU number crunching", "GPU rendering", "Freeing memory"],
             "Waiting tasks don't hold up the others."),
            ("What is the event loop?",
             "The scheduler that runs async tasks and callbacks",
             ["A for loop", "A hardware clock", "One OS thread per task"],
             "It picks up whichever task is ready next."),
            ("What happens if you call time.sleep() inside an async function?",
             "It freezes the event loop, stalling every other task",
             ["It runs faster", "It runs in parallel", "It is ignored"],
             "Use await asyncio.sleep() instead."),
        ],
        "Locks": [
            ("What does a mutex do?",
             "Lets only one thread into a critical section at a time",
             ["Speeds up threads", "Kills threads", "Copies data"],
             "Mutex is short for mutual exclusion."),
            ("What is a deadlock?",
             "Two or more threads waiting forever for each other's locks",
             ["A very fast run", "A normal exit", "A crash on startup"],
             "Thread A holds lock 1 and wants 2; thread B holds 2 and wants 1."),
            ("How can you prevent deadlocks?",
             "Always acquire locks in a consistent global order",
             ["Acquire locks in random order", "Never release locks", "Add more locks"],
             "A consistent order makes circular waiting impossible."),
            ("What does 'with lock:' do in Python?",
             "Acquires the lock and releases it automatically, even on exceptions",
             ["Only acquires the lock", "Releases the lock before the block", "Creates a thread"],
             "The context manager guarantees the release."),
            ("What does a read-write lock allow?",
             "Many readers at once, or a single writer",
             ["Only one reader", "Unlimited writers", "No locking at all"],
             "It suits data that is read far more often than written."),
        ],
    },
    "l10": {
        "Memory": [
            ("How do the stack and the heap differ?",
             "The stack holds call frames and locals; the heap holds dynamically allocated objects",
             ["It's the other way around", "They are the same", "The heap is always faster"],
             "Stack memory is freed automatically when a function returns."),
            ("What is a memory leak?",
             "Memory that is allocated but never freed after it's no longer needed",
             ["A full disk", "CPU overheating", "Stolen RAM"],
             "Usage grows until the program slows down or crashes."),
            ("What does garbage collection do?",
             "Automatically frees memory used by unreachable objects",
             ["Deletes files", "Frees all memory every second", "Requires manual freeing"],
             "Python, Java and JavaScript all use it."),
            ("What is a dangling pointer?",
             "A pointer to memory that has already been freed",
             ["A null pointer, which is always valid", "A pointer to a pointer", "An array"],
             "Using one causes undefined behavior."),
            ("Why does cache locality matter?",
             "Accessing contiguous memory is faster thanks to CPU caches",
             ["Random access is faster", "It only matters for disks", "It has no effect"],
             "Arrays are often faster to scan than linked lists for this reason."),
        ],
        "Git Workflow": [
            ("What does git commit do?",
             "Records a snapshot of the staged changes in your local repository",
             ["Uploads to GitHub", "Deletes files", "Creates a branch"],
             "git push is what uploads commits."),
            ("Why use a feature branch?",
             "To keep work on one feature isolated until it's ready to merge",
             ["To store backups", "To delete main", "To deploy"],
             "main stays stable while features are in progress."),
            ("What causes a merge conflict?",
             "The same lines being changed differently on two branches",
             ["A network error", "An empty commit", "File permissions"],
             "Git can't decide which change to keep."),
            ("What does git pull do?",
             "Fetches remote changes and merges (or rebases) them into your branch",
             ["Pushes your commits", "Deletes the branch", "Stages files"],
             "pull = fetch + merge by default."),
            ("What does git rebase do?",
             "Replays your commits on top of another base for a linear history",
             ["Deletes the remote", "Creates a merge commit", "Adds tags"],
             "Avoid rebasing commits others have already pulled."),
        ],
        "Design Patterns": [
            ("What does the Singleton pattern ensure?",
             "A class has only one instance",
             ["A class has many instances", "No instances exist", "One instance per thread"],
             "It gives global access to that one instance."),
            ("What is the Observer pattern?",
             "Subscribers are notified automatically when a subject changes",
             ["One class watching memory", "A debugging tool", "A database"],
             "Event listeners are a form of Observer."),
            ("What does the Factory pattern do?",
             "Creates objects without the caller naming the exact class",
             ["Destroys objects", "Iterates over objects", "Makes a singleton"],
             "Creation logic lives in one place."),
            ("What is the Strategy pattern?",
             "Swapping interchangeable algorithms at runtime behind a common interface",
             ["Using one algorithm forever", "Hard-coding every case", "Inheritance only"],
             "For example, choosing a sorting or pricing strategy."),
            ("What does the Adapter pattern do?",
             "Converts one interface into another that clients expect",
             ["Supplies power", "Stores data", "Writes logs"],
             "It wraps an incompatible class so it fits."),
        ],
    },
}
