"""Web Development city quizzes."""

LEVELS = {
    "l1": {
        "Elements": [
            ("Which tag is the top-level (largest) heading?",
             "<h1>",
             ["<h6>", "<head>", "<header>"],
             "Headings go from <h1> (most important) to <h6>."),
            ("Which element creates a hyperlink?",
             "<a href=\"…\">",
             ["<link> in the body", "<href>", "<url>"],
             "<link> is for resources like stylesheets, placed in <head>."),
            ("Which of these is a void element (no closing tag)?",
             "<img>",
             ["<div>", "<p>", "<span>"],
             "Void elements like <img>, <br> and <input> have no content."),
            ("How do <div> and <span> differ?",
             "<div> is block-level; <span> is inline",
             ["It's the other way around", "They are identical", "<span> creates a table"],
             "A <div> starts on a new line; a <span> flows with text."),
            ("What is the alt attribute on <img> for?",
             "Text for screen readers, also shown if the image fails to load",
             ["Setting the image size", "Styling the tooltip only", "The file name"],
             "It is essential for accessibility."),
        ],
        "Forms": [
            ("Which input gives built-in email validation?",
             "<input type=\"email\">",
             ["<input type=\"text-email\">", "<email>", "<input type=\"mail\">"],
             "The browser checks the format and mobile keyboards show '@'."),
            ("What does <label for=\"x\"> do?",
             "Links the label to the input with id \"x\", improving accessibility",
             ["Styles the input", "Submits the form", "Hides the input"],
             "Clicking the label also focuses the input."),
            ("With method=\"POST\", form data is sent…",
             "In the request body",
             ["In the URL query string", "Nowhere", "By deleting it"],
             "GET puts the data in the URL instead."),
            ("What does the required attribute do?",
             "Stops the form from submitting while the field is empty",
             ["Makes the field read-only", "Hides the field", "Validates on the server"],
             "It is simple built-in client-side validation."),
            ("Why must you still validate on the server?",
             "Client-side validation can be bypassed",
             ["Browsers never validate", "It is faster", "HTML requires it"],
             "Anyone can send requests directly without using your form."),
        ],
        "Semantics": [
            ("Which of these is a semantic element?",
             "<nav>",
             ["<div>", "<span>", "<b>"],
             "<nav> says what the content is: navigation links."),
            ("What does <main> contain?",
             "The dominant, unique content of the page",
             ["The footer", "All of the sidebars", "The head metadata"],
             "There should be one visible <main> per page."),
            ("Why use semantic HTML?",
             "Better accessibility, better SEO and clearer structure",
             ["A faster CPU", "More colors", "JavaScript requires it"],
             "Screen readers and search engines understand the page better."),
            ("What is <article> for?",
             "Self-contained content that could stand alone, like a blog post",
             ["Navigation", "Only sidebar ads", "Scripts"],
             "It could be syndicated or reused on its own."),
            ("How do <strong> and <b> differ?",
             "<strong> marks importance; <b> is only visual bold",
             ["They are identical", "<b> is the semantic one", "<strong> is italic"],
             "Screen readers may emphasize <strong>."),
        ],
    },
    "l2": {
        "Box Model": [
            ("What are the box model layers, from the inside out?",
             "Content, padding, border, margin",
             ["Margin, border, padding, content", "Content, margin, border, padding", "Padding, content, margin, border"],
             "Padding sits inside the border; margin sits outside it."),
            ("What does box-sizing: border-box do?",
             "Makes width include the padding and border",
             ["Makes width exclude the padding and border", "Only affects the margin", "Only affects the height"],
             "It makes sizing much more predictable."),
            ("width: 200px, padding: 10px, border: 5px, box-sizing: content-box. What is the total rendered width?",
             "230px",
             ["200px", "215px", "220px"],
             "200 + 10·2 + 5·2 = 230."),
            ("What is margin collapsing?",
             "Adjacent vertical margins combining into the larger one",
             ["Margins adding together", "Horizontal margins merging", "Margins disappearing entirely"],
             "Two 20px vertical margins produce a 20px gap, not 40px."),
            ("How do padding and margin differ?",
             "Padding is inside the border (the background shows); margin is outside",
             ["It's the other way around", "They are the same", "Margin is inside the border"],
             "Margin is always transparent space."),
        ],
        "Flexbox": [
            ("How do you turn a container into a flexbox?",
             "display: flex",
             ["flex: on", "layout: flex", "position: flex"],
             "Its direct children become flex items."),
            ("What does justify-content control?",
             "Alignment along the main axis",
             ["Alignment along the cross axis", "The font", "The grid"],
             "With the default row direction, that is horizontal."),
            ("In a row flex container, what does align-items: center do?",
             "Centers items vertically (on the cross axis)",
             ["Centers items horizontally", "Makes items wrap", "Changes their order"],
             "align-* works on the cross axis."),
            ("What does flex: 1 on an item do?",
             "Makes it grow to share the free space equally with its siblings",
             ["Fixes its width at 1px", "Hides it", "Creates one column"],
             "It is shorthand for flex-grow: 1 (plus shrink and basis)."),
            ("What does flex-direction: column do?",
             "Makes the main axis vertical",
             ["Makes the main axis horizontal", "Reverses the rows", "Turns it into a grid"],
             "justify-content then controls vertical alignment."),
        ],
        "Grid": [
            ("What does grid-template-columns: repeat(3, 1fr) create?",
             "Three equal-width columns",
             ["Three 3px columns", "One column that is 3fr wide", "Three rows"],
             "Each column takes one fraction of the free space."),
            ("What does the fr unit mean?",
             "A fraction of the remaining free space",
             ["A frame", "A font size", "A fixed rem value"],
             "1fr 2fr splits the space 1:2."),
            ("How does CSS Grid differ from Flexbox?",
             "Grid is two-dimensional; Flexbox is mainly one-dimensional",
             ["It's the other way around", "They are the same", "Grid is only for text"],
             "Grid controls rows and columns at the same time."),
            ("What does the gap property set?",
             "The space between rows and columns",
             ["Padding outside the grid", "The border", "The page margin"],
             "It spaces items without needing extra margins."),
            ("What does grid-column: 1 / 3 do?",
             "Spans from line 1 to line 3, covering two columns",
             ["Spans three columns", "Covers column 1 only", "Covers column 3 only"],
             "The numbers refer to grid lines, not columns."),
        ],
    },
    "l3": {
        "DOM": [
            ("What is the DOM?",
             "A tree representation of the page that JavaScript can read and change",
             ["A database", "A server", "A CSS file"],
             "The Document Object Model."),
            ("Which method selects the first element matching a CSS selector?",
             "document.querySelector()",
             ["document.getElementByClass()", "document.selectCSS()", "document.find()"],
             "querySelectorAll() returns every match."),
            ("How do textContent and innerHTML differ?",
             "innerHTML parses HTML (an XSS risk with user input); textContent inserts plain text",
             ["They are identical", "textContent parses HTML", "innerHTML is the safer one"],
             "Use textContent for untrusted data."),
            ("How do you create a new element in JavaScript?",
             "document.createElement(\"li\")",
             ["new Element(\"li\")", "html(\"li\")", "document.add(\"li\")"],
             "Then insert it with appendChild or append."),
            ("Why put scripts at the end of <body> or use defer?",
             "So the DOM elements exist before the script runs",
             ["It makes downloads faster", "It is required by the spec", "It affects CSS"],
             "Otherwise querySelector may return null."),
        ],
        "Events": [
            ("How do you attach a click handler?",
             "el.addEventListener(\"click\", handler)",
             ["el.click = listen", "el.on(\"click\") (native DOM)", "el.event(\"click\")"],
             "You can attach several listeners to the same event."),
            ("What does event.preventDefault() do?",
             "Stops the browser's default action, such as submitting a form",
             ["Stops the event bubbling", "Deletes the element", "Reloads the page"],
             "stopPropagation() is what stops bubbling."),
            ("What is event bubbling?",
             "An event travels from the target up through its ancestors",
             ["It travels down only", "It goes nowhere", "It jumps to a random element"],
             "A click on a button also reaches its parent div."),
            ("What is event delegation?",
             "One listener on a parent handles events from many children",
             ["A listener on every child", "Using no listeners", "Using timers"],
             "It relies on bubbling and works for elements added later."),
            ("What is event.target?",
             "The element that originally triggered the event",
             ["Always the document", "The element the listener is attached to", "The window"],
             "The listener's element is event.currentTarget."),
        ],
        "ES Modules": [
            ("How do you write a named export?",
             "export function add() {}",
             ["public function add() {}", "export: add()", "#export add"],
             "Import it with import { add } from './math.js'."),
            ("How do you import a module's default export?",
             "import add from \"./math.js\"",
             ["const add = include(\"./math.js\")", "#include math", "using math"],
             "Default imports don't use curly braces."),
            ("What does <script type=\"module\"> do?",
             "Enables import/export and defers the script by default",
             ["Inlines CSS", "Disables JavaScript", "Blocks HTML parsing"],
             "Modules also run in strict mode."),
            ("What is a benefit of ES modules?",
             "Each file has its own scope, with explicit dependencies",
             ["Global variables everywhere", "Slower loading", "No code reuse"],
             "Nothing leaks unless it is exported."),
            ("How do named and default exports differ?",
             "A module can have many named exports but only one default",
             ["A module can have many defaults", "Named exports aren't allowed", "They are the same"],
             "Mixing both in one module is fine."),
        ],
    },
    "l4": {
        "Media Queries": [
            ("When does @media (max-width: 600px) apply?",
             "When the viewport is 600px wide or narrower",
             ["When it is 600px or wider", "Only when printing", "Only at exactly 600px"],
             "max-width means 'up to'."),
            ("Which tag makes mobile browsers use the device width?",
             "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
             ["<viewport>", "<meta charset=\"utf-8\">", "<meta http-equiv=\"refresh\">"],
             "Without it, phones render a zoomed-out desktop layout."),
            ("What does prefers-color-scheme detect?",
             "The user's dark or light mode preference",
             ["The screen size", "The language", "The battery level"],
             "@media (prefers-color-scheme: dark) { … }"),
            ("What is a breakpoint?",
             "A width at which the layout changes",
             ["A JavaScript error", "A CSS bug", "A network failure"],
             "Choose breakpoints where your content breaks, not by device."),
            ("Which units scale with their context?",
             "rem, % and vw",
             ["px only", "pt only", "cm"],
             "Relative units adapt to font size and viewport."),
        ],
        "Mobile First": [
            ("What does mobile-first mean?",
             "Base styles target small screens; min-width queries add larger layouts",
             ["Design for desktop first", "Build a separate mobile site", "Use no CSS"],
             "You enhance progressively as space grows."),
            ("Mobile-first stylesheets mostly use which media feature?",
             "min-width",
             ["max-width", "orientation only", "print"],
             "Each query adds styles once the screen is at least that wide."),
            ("What is the recommended minimum touch-target size?",
             "About 44×44 CSS pixels",
             ["10×10 px", "5 px", "There is no minimum"],
             "Small targets are hard to tap accurately."),
            ("How do you serve appropriately sized images?",
             "srcset and <picture>",
             ["Always send the largest image", "Use CSS only", "Use GIFs"],
             "The browser picks the best file for the screen."),
            ("Why design mobile-first?",
             "It forces you to prioritize essential content and performance",
             ["Mobile has no users", "Desktop is impossible", "HTML requires it"],
             "Constraints lead to leaner, clearer pages."),
        ],
        "Accessibility": [
            ("What does WCAG stand for?",
             "Web Content Accessibility Guidelines",
             ["Web CSS Accessibility Grid", "World Content App Guide", "Web Code Audit Group"],
             "WCAG is the main accessibility standard."),
            ("What is the WCAG AA minimum contrast for normal text?",
             "4.5 : 1",
             ["1 : 1", "2 : 1", "10 : 1"],
             "Large text only needs 3 : 1."),
            ("What do keyboard users need?",
             "Every interactive element reachable with the keyboard, with a visible focus",
             ["Mouse-only controls", "Hidden focus outlines", "No Tab support"],
             "Test your page using only Tab, Enter and Space."),
            ("What is the first rule of ARIA?",
             "Prefer native semantic HTML; use ARIA only when needed",
             ["Use ARIA everywhere", "ARIA replaces HTML", "Use ARIA for styling"],
             "A real <button> beats <div role=\"button\">."),
            ("Why use <button> instead of a clickable <div>?",
             "You get keyboard support and the correct role for free",
             ["A <div> is better", "They behave the same", "Buttons can't be styled"],
             "A <div> needs tabindex, a role and key handlers to match."),
        ],
    },
    "l5": {
        "Components": [
            ("What is a UI component?",
             "A reusable, self-contained piece of UI with its own markup and logic",
             ["A database", "A server", "A CSS reset"],
             "Pages are built by combining components."),
            ("What are props?",
             "Inputs passed from a parent component to a child",
             ["Global variables", "CSS rules", "Data sent directly from child to parent"],
             "Props flow down; events or callbacks flow up."),
            ("What is JSX?",
             "HTML-like syntax that compiles to JavaScript function calls",
             ["A new language that replaces JavaScript", "A CSS dialect", "A database query language"],
             "<div /> becomes a call like React.createElement('div')."),
            ("Why do list items need keys?",
             "So the framework can tell which items changed and update efficiently",
             ["For styling", "For encryption", "For SEO"],
             "Use stable IDs, not array indexes, when the list can change."),
            ("What is composition in component design?",
             "Building complex UIs by nesting smaller components",
             ["One giant component", "Inheritance only", "Writing CSS"],
             "Small components are easier to test and reuse."),
        ],
        "State": [
            ("What is state in a frontend framework?",
             "Data that changes over time and triggers a re-render",
             ["A constant", "A CSS value", "An HTML attribute"],
             "When state changes, the UI updates to match."),
            ("What does React's useState return?",
             "The current value and a setter function",
             ["Only the value", "A Promise", "A DOM element"],
             "const [count, setCount] = useState(0)."),
            ("What happens if you mutate React state directly, e.g. arr.push(x)?",
             "The UI may not re-render; you should set a new copy instead",
             ["It always works", "It is faster", "It is required"],
             "React compares references to detect changes."),
            ("What does 'lifting state up' mean?",
             "Moving shared state to the closest common parent",
             ["Moving it into global CSS", "Duplicating it in every child", "Deleting it"],
             "Siblings then receive it through props."),
            ("Which of these is a global state library?",
             "Redux (or Zustand, Pinia)",
             ["Express", "Webpack", "Postgres"],
             "They manage state shared across many components."),
        ],
        "Routing": [
            ("What is client-side routing?",
             "Changing views without full page reloads by updating the URL with the History API",
             ["The server rendering every page", "DNS lookup", "CSS"],
             "It is how single-page apps navigate."),
            ("What does history.pushState() do?",
             "Changes the URL without reloading the page",
             ["Reloads the page", "Deletes the history", "Downloads a file"],
             "The router then renders the matching view."),
            ("In the route /users/:id, what is :id?",
             "A parameter captured from the URL",
             ["A CSS id", "An auto-generated database key", "A query string only"],
             "/users/42 gives id = \"42\"."),
            ("How must a server be set up for SPA deep links to work?",
             "Fall back to index.html for all app routes",
             ["Disable JavaScript", "Return 404 for every route", "Use separate servers"],
             "Otherwise refreshing /about returns a 404."),
            ("What is route-based lazy loading?",
             "Loading a route's code only when it is visited",
             ["Loading everything up front", "Making the app slower", "Removing routes"],
             "The initial bundle gets smaller."),
        ],
    },
    "l6": {
        "REST": [
            ("How are resources identified in REST?",
             "By URLs",
             ["Only by cookies", "By port numbers", "By CSS classes"],
             "For example, /users/42 is one user resource."),
            ("Which HTTP method creates a new resource?",
             "POST",
             ["GET", "DELETE", "HEAD"],
             "POST /users creates a user."),
            ("Which HTTP method should be safe, with no side effects?",
             "GET",
             ["POST", "DELETE", "PUT"],
             "GET should only read data."),
            ("What does statelessness mean in REST?",
             "Each request carries all the information needed; the server keeps no session between requests",
             ["The server remembers everything", "There are no URLs", "Only one request is allowed"],
             "Stateless servers are easier to scale."),
            ("Which is a RESTful URL for listing a user's orders?",
             "GET /users/42/orders",
             ["GET /getOrdersForUser?id=42&action=get", "POST /users/42/orders/delete", "GET /orders.php?do=list"],
             "Use nouns for resources and the HTTP method for the action."),
        ],
        "Fetch": [
            ("What does fetch() return?",
             "A Promise that resolves to a Response",
             ["The JSON data directly", "A string", "An XMLHttpRequest"],
             "You then read the body with .json() or .text()."),
            ("How do you parse a JSON response body?",
             "await response.json()",
             ["JSON.parse(response)", "response.body.json", "response.text().json"],
             "response.json() returns a Promise too."),
            ("When does a fetch() Promise reject?",
             "Only on network failure, not on HTTP 404 or 500",
             ["On any non-200 status", "Never", "On any redirect"],
             "Check response.ok for HTTP errors."),
            ("How do you POST JSON with fetch?",
             "method: \"POST\", a Content-Type: application/json header, and body: JSON.stringify(data)",
             ["body: data as a plain object", "Use GET with a body", "Put the JSON in the URL"],
             "The body must be a string, not an object."),
            ("What is CORS?",
             "A browser security mechanism that controls cross-origin requests using server headers",
             ["A CSS library", "A compression format", "A caching layer"],
             "The server must send Access-Control-Allow-Origin."),
        ],
        "Status Codes": [
            ("What does HTTP 404 mean?",
             "Not Found",
             ["Internal Server Error", "OK", "Unauthorized"],
             "The requested resource doesn't exist."),
            ("What does HTTP 201 mean?",
             "Created",
             ["No Content", "A redirect", "An error"],
             "It is typically returned after a successful POST."),
            ("What do 5xx status codes indicate?",
             "Server errors",
             ["Client errors", "Success", "Redirects"],
             "4xx codes are client errors."),
            ("How do 401 and 403 differ?",
             "401 means not authenticated; 403 means authenticated but not allowed",
             ["It's the other way around", "They are the same", "Both are server errors"],
             "401: log in first. 403: you don't have permission."),
            ("What does HTTP 301 mean?",
             "Moved Permanently (a redirect)",
             ["Not Modified", "A temporary redirect", "Bad Request"],
             "Browsers and search engines update to the new URL."),
        ],
    },
    "l7": {
        "Servers": [
            ("What does a web server do?",
             "Listens for HTTP requests and sends back responses",
             ["Renders CSS in the browser", "Only stores data", "Resolves DNS"],
             "Frameworks like Express and FastAPI run on top of one."),
            ("What does localhost:8000 refer to?",
             "Port 8000 on your own machine",
             ["A remote server", "A public website", "An external IP address"],
             "localhost resolves to 127.0.0.1."),
            ("Why do stateless servers scale well?",
             "Any instance can handle any request, so adding servers is easy",
             ["They need no memory", "They store no data anywhere", "They are slower"],
             "Session data lives in a shared store instead."),
            ("Why keep secrets in environment variables?",
             "It keeps secrets out of the source code",
             ["It is faster", "HTTP requires it", "It makes them public"],
             "Never commit API keys to git."),
            ("What does a reverse proxy such as Nginx do?",
             "Sits in front of app servers to route traffic, balance load and handle TLS",
             ["Runs as a browser plugin", "Acts as a database", "Compiles CSS"],
             "Clients only ever talk to the proxy."),
        ],
        "Routing": [
            ("What is a backend route?",
             "A mapping from an HTTP method and URL path to a handler",
             ["A network cable", "The browser's URL bar", "A CSS rule"],
             "For example, GET /users → listUsers()."),
            ("In Express, app.get(\"/users/:id\", …) handles /users/7. What is req.params.id?",
             "\"7\" (a string)",
             ["7 (a number)", "undefined", "\"/users/7\""],
             "Route parameters are always strings."),
            ("In Express, how do you read ?page=2 from the URL?",
             "req.query.page",
             ["req.params.page", "req.body.page", "req.page"],
             "Query strings are parsed into req.query."),
            ("Can one path have different handlers for different methods?",
             "Yes: GET /items lists items and POST /items creates one",
             ["No, it's not allowed", "They must share one handler", "It causes an error"],
             "The method plus the path identifies the route."),
            ("Why does route order matter?",
             "The first matching route handles the request, so specific routes go before catch-alls",
             ["Routes are sorted alphabetically", "The order is random", "The last route wins"],
             "A catch-all '*' route placed first would swallow everything."),
        ],
        "Middleware": [
            ("What is middleware?",
             "Functions that run between receiving a request and the final handler",
             ["A database", "Hardware", "Frontend code"],
             "They form a pipeline for every request."),
            ("What are typical middleware jobs?",
             "Logging, auth checks and parsing JSON bodies",
             ["GPU rendering", "Compiling CSS", "DNS lookups"],
             "These are cross-cutting concerns shared by many routes."),
            ("In Express, what does next() do?",
             "Passes control to the next middleware",
             ["Ends the response", "Restarts the server", "Skips every remaining handler"],
             "Call next(err) to jump to the error handler."),
            ("What happens if middleware neither calls next() nor sends a response?",
             "The request hangs",
             ["A response is sent automatically", "It runs faster", "The server crashes"],
             "The client waits until it times out."),
            ("An Express error-handling middleware takes how many arguments?",
             "Four: (err, req, res, next)",
             ["None", "Two", "Five"],
             "The four-argument signature is how Express recognizes it."),
        ],
    },
    "l8": {
        "SQL": [
            ("Which SQL keyword retrieves rows?",
             "SELECT",
             ["GET", "FETCH ROWS", "PULL"],
             "SELECT name FROM users;"),
            ("What does WHERE do?",
             "Filters rows by a condition",
             ["Sorts rows", "Groups rows", "Joins tables"],
             "ORDER BY sorts; GROUP BY groups."),
            ("What does an INNER JOIN return?",
             "Rows with matching values in both tables",
             ["Every row from both tables", "Only rows from the left table", "Always the full cartesian product"],
             "Rows without a match are dropped."),
            ("What is a primary key?",
             "A column (or set of columns) that uniquely identifies each row",
             ["Any column", "A password", "A foreign table"],
             "It must be unique and not null."),
            ("What do parameterized queries prevent?",
             "SQL injection",
             ["Slow typing", "Large databases", "Styling issues"],
             "User input is sent as data, never as SQL code."),
        ],
        "ORMs": [
            ("What is an ORM?",
             "An Object-Relational Mapper that maps database tables to classes and objects",
             ["An Object Rendering Machine", "An Online Resource Manager", "An Output Routing Module"],
             "Rows become objects you work with in code."),
            ("Which of these is an ORM?",
             "SQLAlchemy",
             ["React", "Nginx", "Webpack"],
             "Others include Prisma, Django ORM and Sequelize."),
            ("What is the N+1 query problem?",
             "One query for a list plus one extra query per item, fixed with eager loading or joins",
             ["Running N+1 servers", "Adding one extra column", "Making one query too few"],
             "Loading 100 posts' authors one by one means 101 queries."),
            ("What is a benefit of using an ORM?",
             "Less boilerplate SQL and more database-agnostic code",
             ["It is always faster than SQL", "No database is needed", "Nothing to learn"],
             "You write code in your language's idioms."),
            ("What is a downside of ORMs?",
             "They can generate inefficient queries and hide the SQL being run",
             ["They can't store data", "They don't support joins", "They can't be used from Python"],
             "Always check the generated SQL for hot paths."),
        ],
        "Migrations": [
            ("What is a database migration?",
             "A versioned script that changes the database schema",
             ["Moving to new servers", "A backup", "Moving data abroad"],
             "Migrations run in order, like commits for your schema."),
            ("Why use migrations?",
             "Schema changes are tracked in version control and applied consistently everywhere",
             ["To delete data", "To make queries faster", "For CSS"],
             "Every environment ends up with the same schema."),
            ("Which of these is a migration tool?",
             "Alembic (or Prisma Migrate, Rails migrations)",
             ["Figma", "Babel", "ESLint"],
             "Alembic pairs with SQLAlchemy."),
            ("What is a 'down' migration?",
             "One that reverts the changes made by the 'up' migration",
             ["One that applies the change twice", "One that deletes the database", "An upgrade"],
             "It lets you roll back a bad deploy."),
            ("How do you safely add a NOT NULL column to a big, live table?",
             "Add it as nullable (or with a default), backfill it, then add the constraint",
             ["Add it as NOT NULL right away while the app runs", "Drop the table", "Ignore the constraint"],
             "Doing it in steps avoids failures and long locks."),
        ],
    },
    "l9": {
        "Sessions": [
            ("How does session-based authentication work?",
             "The server stores session data; the browser holds a session-ID cookie",
             ["The browser stores the password", "No cookies are used", "The token goes in the URL"],
             "Each request sends the cookie, and the server looks up the session."),
            ("What does the HttpOnly cookie flag do?",
             "Stops JavaScript from reading the cookie, limiting XSS theft",
             ["Encrypts the cookie automatically", "Sends it over HTTP but not HTTPS", "Makes it expire instantly"],
             "document.cookie can't see HttpOnly cookies."),
            ("What does the Secure cookie flag do?",
             "Only sends the cookie over HTTPS",
             ["Encrypts the cookie's contents", "Makes it readable by JavaScript", "Blocks all third parties"],
             "It stops the cookie leaking over plain HTTP."),
            ("How do you prevent session fixation?",
             "Generate a new session ID after login",
             ["Reuse the same session ID", "Put the session ID in the URL", "Never expire sessions"],
             "An attacker's pre-set ID becomes useless."),
            ("What should logging out do?",
             "Invalidate the session on the server",
             ["Only hide the logout button", "Clear the browser history", "Restart the server"],
             "Deleting only the cookie leaves the session usable if it was stolen."),
        ],
        "JWT": [
            ("What are the three parts of a JWT?",
             "Header, payload, signature",
             ["Username, password, token", "Key, value, hash", "Head, body, footer"],
             "They are base64url-encoded and joined with dots."),
            ("A JWT payload is…",
             "Base64url-encoded, not encrypted, so anyone can read it",
             ["Encrypted", "Hashed", "A compressed secret"],
             "Never put secrets in a JWT payload."),
            ("What does a JWT's signature guarantee?",
             "The token hasn't been tampered with",
             ["The data is hidden", "The request is faster", "The token is compressed"],
             "Changing the payload invalidates the signature."),
            ("What is a drawback of JWTs?",
             "They are hard to revoke before they expire without extra infrastructure",
             ["They can't hold any data", "They are always too long to send", "They are never signed"],
             "A stolen token stays valid until it expires."),
            ("Why use short-lived access tokens with refresh tokens?",
             "To limit the damage if an access token leaks",
             ["To make tokens permanent", "To remove the signature", "To avoid expiry altogether"],
             "Refresh tokens can be revoked server-side."),
        ],
        "XSS / CSRF": [
            ("What is XSS (cross-site scripting)?",
             "Injecting malicious scripts into pages that other users view",
             ["Cross-site CSS", "A kind of SQL error", "A DDoS attack"],
             "The script runs with the victim's session."),
            ("How do you prevent XSS?",
             "Escape output, avoid innerHTML with user data, and use a Content Security Policy",
             ["Store passwords in plain text", "Disable HTTPS", "Use bigger fonts"],
             "Treat all user input as untrusted."),
            ("What is CSRF?",
             "Tricking a logged-in user's browser into sending unwanted requests to a site",
             ["Stealing the database directly", "Injecting a script", "Overloading the server"],
             "The browser attaches the user's cookies automatically."),
            ("Which are CSRF defenses?",
             "CSRF tokens and SameSite cookies",
             ["Longer passwords alone", "Hiding URLs", "Using GET for state changes"],
             "Both stop other sites from forging valid requests."),
            ("What does a Content-Security-Policy header do?",
             "Restricts which sources scripts and other resources can load from",
             ["Compresses responses", "Caches pages", "Resolves DNS"],
             "It blocks many injected scripts from running."),
        ],
    },
    "l10": {
        "Build Tools": [
            ("What does a bundler such as Vite or Webpack do?",
             "Combines and optimizes modules for the browser",
             ["Runs a database", "Hosts the site", "Runs the tests"],
             "It turns many source files into a few optimized ones."),
            ("What is minification?",
             "Removing whitespace and shortening names to shrink files",
             ["Adding comments", "Encrypting the code", "Translating the code"],
             "Smaller files download faster."),
            ("What is tree shaking?",
             "Removing unused exported code from the bundle",
             ["Planting trees", "Deleting source files", "Sorting imports"],
             "ES module syntax makes unused exports detectable."),
            ("Why add a content hash to filenames, like app.3f9a.js?",
             "Cache busting: a new hash means browsers fetch the new file",
             ["Security", "SEO", "Debugging"],
             "Unchanged files can be cached forever."),
            ("What are source maps for?",
             "Mapping minified code back to the original source for debugging",
             ["Generating a site map", "Storing data", "GPS"],
             "DevTools can then show your original files."),
        ],
        "Hosting": [
            ("What is static hosting a good fit for?",
             "HTML, CSS and JavaScript with no server code (e.g. Netlify, GitHub Pages)",
             ["Databases", "Long-running Python servers", "WebSocket servers"],
             "The files are served as-is, often from a CDN."),
            ("What does a CDN do?",
             "Serves content from servers close to users, making it faster",
             ["Debugs code", "Stores the database", "Preprocesses CSS"],
             "Content Delivery Network."),
            ("What does HTTPS require?",
             "A TLS certificate, e.g. from Let's Encrypt",
             ["A bigger server", "Special HTML", "A faster CPU"],
             "The certificate proves the domain's identity."),
            ("What does DNS do?",
             "Maps domain names to IP addresses",
             ["Compresses files", "Hosts files", "Styles pages"],
             "It is the internet's phone book."),
            ("What is horizontal scaling?",
             "Adding more server instances behind a load balancer",
             ["Buying one bigger machine", "Using fewer servers", "Writing more CSS"],
             "A bigger single machine is vertical scaling."),
        ],
        "CI/CD": [
            ("What is Continuous Integration (CI)?",
             "Automatically building and testing every change that is pushed",
             ["Only humans reviewing code", "Deploying by hand", "Doing nothing"],
             "Bugs get caught soon after they are introduced."),
            ("What is Continuous Delivery/Deployment (CD)?",
             "Automatically releasing builds that pass the pipeline",
             ["Continuous debugging", "Continuous design", "Continuous deletion"],
             "Small, frequent releases are less risky."),
            ("Where are GitHub Actions workflows defined?",
             "In YAML files under .github/workflows",
             ["Only in package.json", "In the Dockerfile", "In the README"],
             "Each workflow lists its triggers, jobs and steps."),
            ("What should happen when tests fail in CI?",
             "The merge or deploy is blocked until they're fixed",
             ["The failure is ignored", "It deploys anyway", "The tests get deleted"],
             "A red pipeline protects the main branch."),
            ("What is a rollback?",
             "Reverting to the previous working version when a release breaks",
             ["Deleting the database", "Rolling dice", "Stopping CI forever"],
             "Fast rollbacks make deploying less scary."),
        ],
    },
}
